### ISSUE TITLE
Download support for uv and curl

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#1003]
Support
`-DDOWNLOAD_CURL=ON|ALWAYS`
`-DDOWNLOAD_UV=ON|ALWAYS`
inline with sodium to make building releases easier

**Comment by majestrate** [comment]
there is a makefile target for libuv already (not cmake) and it is used by android and ios, if you want to use that with static build follow the same codepath as that.

**Comment by majestrate** [comment]
added in https://github.com/loki-project/loki-network/pull/1005 with docs
