### ISSUE TITLE
Debian: Installing on NFS root fails

### ISSUE THREAD

**Issue by cathugger** [loki-project/loki-network#1007]
**Describe the bug**
on my debian (technically raspbian) NFS root installation lokinet-bin package fails to install
I think issue is in https://github.com/loki-project/loki-network/blob/master/debian/postinst script, maybe it needs `exit 0` at the end, or `-e` flag removed.

**To Reproduce**
have debian install ontop of NFS
try installing lokinet from official lokinet-provided debian repo

**Screenshots Or Logs**
```
Setting up lokinet-bin (0.6.1-1~deb10) ...
adduser: Warning: The home directory `/var/lib/lokinet' does not belong to the user you are currently creating.
Failed to set capabilities on file `/usr/bin/lokinet' (Operation not supported)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
failed to setcap lokinet
dpkg: error processing package lokinet-bin (--configure):
 installed lokinet-bin package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of lokinet:
 lokinet depends on lokinet-bin (= 0.6.1-1~deb10); however:
  Package lokinet-bin is not configured yet.

dpkg: error processing package lokinet (--configure):
 dependency problems - leaving unconfigured
```

**Device and Operating system (please complete the following information):**
 - OS: Debian/Raspbian on NFS
-  Device: irrelevant, should affect any NFS-rooted installation
 - Lokinet Version number or Git commit hash: 0.6.1

**Comment by jagerman** [comment]
The fundamental issue here is that the binary needs that `setcap` in order to run, and NFS just doesn't support `setcap` (at least, not the setcaps we need here).  Removing the `-e` will install the binary, but it won't be usable, and so I'm reluctant to silently ignore such a failure.

(Also, the debian packaging used to build the public debs is kept separate in the `debian/buster` branch rather than master; the debian stuff in master is mainly there to produce a quick and dirty deb for local use.)

There is one possible way to fix this, which is to move the capabilities into the systemd service file rather than setcap'ing the binary, which I'll investigate for 0.6.3.

**Comment by jagerman** [comment]
> I'll investigate for 0.6.3.

... or 0.6.2-3, coming soon.  (You're on ARM, and those take a few hours to build, but should be ready later tonight).

**Comment by jagerman** [comment]
ARM debs should be updated now to 0.6.2-3, if you want to test this against your NFS root.

**Comment by cathugger** [comment]
0.6.2-3 actually installed allright, thanks.
haven't tested systemd unit as I don't run systemd, but it works with my daemontools setup fine.
btw, 0.6.3 got tagged, but it seems it's not in repo yet (at least for arm), guess I'll have to wait for that..

**Comment by jagerman** [comment]
It should be there now, the arm builds usually just lag the amd64/i386 builds by a day because it takes a lot longer to build on my Pi 4.

For your daemontools setup, did you figure out how to assign capabilities to the process?

**Comment by cathugger** [comment]
Yeah, it is there now.
For daemontools I currently just run it as root and that works.
I'm also looking into trying doing it with `capsh` command, but haven't tested that yet.

**Comment by cathugger** [comment]
seems like libcap's capsh in current stable debian doesn't support `--addamb` for ambient capabilities so I won't be using that at least on that machine.
in any case I guess this can now be closed, as original issue of stuff not installing is now fixed.
