### ISSUE TITLE
Gossip protocol for router snode propagation

### ISSUE THREAD

**Issue by jagerman** [loki-project/loki-network#1055]
RC propagation for routers right now is a bit backwards: each router does DHT lookups for router RCs that it doesn't have. The ideas in #1047 improves this a bit, but it can still be improved more by pushing RCs across the network rather than trying to pull them over DHT.

The idea here would be similar to what lokid does to propagate uptime proofs:
- once per hour*, a router broadcasts its RC to its peers, who pass it to their peers, etc.
- RCs are not accepted if there is already an existing known RC for that router with a timestamp less than half an hour old.
- RCs don't get accepted if they have a timestamp too far from the current time (perhaps 10 mins?)
- RCs go stale after 2h5m (mirroring lokid's uptime proof expiry).

We still need the ability to pull them from other routers as a fallback for an edge case where a router has newly started up (or been offline for a couple hours and thus expires all its RCs on startup), doesn't have the RCs yet, but needs one for an incoming request.  This is going to be the exception rather than the rule, however: the vast majority of the time the gossiped RCs will be used.  This does not need to be a recursive request: it should be fine to query all our peers non-recursively which is going to be fine unless *all* my peers have also been offline, which is unlikely.

* it might be worth slightly randomizing this so that even if someone restarts 30 lokinet's at once the actual transmission will be spread out a bit over time instead of being clustered in the same second every hour (I've been thinking about doing something like this for lokid as well).  Perhaps something like: when we send an RC we also choose the time to transmit the next RC update from current time plus a random draw from [45m, 60m].

**Comment by KeeJef** [comment]
Agree that a more gossip style protocol where RC's are pushed instead of pulled is probably going to lead to a much better connected network. Routers are online enough that even after hours they should have a very reliable view of the network.

**Comment by majestrate** [comment]
this was added in 0.7.0
