### ISSUE TITLE
Non-DHT client introset lookups

### ISSUE THREAD

**Issue by jagerman** [loki-project/loki-network#1057]
# Problem

The current DHT lookup is not ideal for fast introset lookups (and thus path builds).  The problem is that router interconnections don't have any correlation between closeness of the introset.  As an example consder this established router connection diagram:

![image](https://user-images.githubusercontent.com/4459524/72649720-ceee9600-3954-11ea-8b3a-cb6f762cabe3.png)

where we know that R₆ holds the introset (call it `T`) that we want - i.e. `R₆ ^ T` is closest to the looked up introset.  The problem is that we have no way to determine a good way to reach R₆ from R₁.  Currently with DHT lookups we do recursive lookups starting with whichever of `R₂ ^ T` or `R₃ ^ T` is smaller, but there's no correlation between established router-to-router connections and the destination.

The end result is that it's entirely possible that we hit a worst case traversal in my diagram where we rank the nodes by closeness to T as: `R₆ < R₄ < R₅ < R₃ < R₂` and so a DHT lookup of T starting at R₁ is going to query R₃, get a not-found result, then try R₂, which tries R₄, gets a not found, then tries R₅.

Basically there's no way to know which of our router peers are closest to R₆ and without that there's no obvious way that we can get the "good" DHT traversal (R₁ -> R₂ -> R₅ -> R₆) here: closeness of peers to T is basically no better than random (except at the very last hop from R₅ -> R₆).

# Proposed solution

Rather than doing a DHT lookup, we can simply have the client determine that it needs to talk to R₆ and build a path from itself to R₆, then query R₆ directly for the record.  (In reality we'd want the introset to be stored redundantly, perhaps on the 5 closest nodes, in case one fails we call fallback to the second-closest, etc.).

There is at least one thing still to work out here: This requires that a client know about most of the routers on the network, because it needs to be able to calculate R₆.  This is a potential issue for a "fresh" client because it will usually only know a relatively small number of RCs.

One potential solution to this is to download the full set of RCs during initialization.  This is not going to be all that small: each RC is ~290 bytes, so for 1000 routers that's 300kB + overhead, and increases as the number of SNs increases.

An alternative is to download a smaller list of just router pubkeys (which would be 32 bytes * number of routers, so about 32kB plus overhead for 1000 nodes).  The list of pubkeys gives us enough to calculate R₆, but we would also then need some way to then query R₆'s RC from the routers we are connected to so that we can build a path to it.  That lets us build a path using routers we do know about that ends on R₆ and we can use that path to request the introset directly from R₆.

**Comment by KeeJef** [comment]
300KB is tiny, and i don't see the router count growing over 2000 Nodes any time soon, so this growth should not be too bad, we should just have the client download the RC list from a Seed Node on first use, then you can just query the nodes you have in your DB every time after that first "Bootstrapping"

**Comment by jagerman** [comment]
The RCs refresh continuously, it isn't like the bootstrap that you can just download once.  It would be 300kB (and probably more like 1MB with growth + overhead) pretty much every time you start it up, including on mobile.

**Comment by jagerman** [comment]
It might also be worth exploring making clients keep RCs briefly at startup to use as potential boostrap sources so that they can avoid needing to go back to the bootstrap node.  On startup it can pick a few, try to connect to them and, if they work, use them.  Then the trust required in the bootstrap goes down - you typically need to trust it once or if it's been a very long time since you were last up, but not every time you start up after more than a few hours.

**Comment by jagerman** [comment]
Some more info on this:

In order for Kademlia to work for DHT traversal you must know about, and consider as peers for traversal, enough of the network to have variation in each bit of the router IDs.  This means that at each step you are guaranteed to be able to get closer to the target because you can always essentially eliminate the most significant bit (and in many cases more than one significant bit).

The existing code is only considering routers we have existing sessions with, and these connections are not based on Kademlia characteristics at all -- instead they are just randomly established initially, and then randomly established by clients building paths through them.

The fix for this is to consider all routers (not established session routers).  This is actually going to collapse to a single step in the vast majority of cases since every router knows every other router and so on any router finding the closest router is almost always going to be the target.

**Comment by hackervera** [comment]
> 300KB is tiny, and i don't see the router count growing over 2000 Nodes any time soon

> 640K is more memory than anyone will ever need on a computer
