### ISSUE TITLE
lokinet-win32 ui

### ISSUE THREAD

**Issue by despair86** [loki-project/loki-network#107]
currently working on a .NET-based UI for windows lokinet

- .net CLR v2 or v4.x
- some recent version of C# (probably v6+ so long as `csc` doesn't yell at me when emitting the CLR v2 IL)
- may make it resemble the qt5 ui once someone mocks something up for _that_
- side benefit: it is projected to be a single-file binary, _might_ break up certain common functionality in class libs if warranted
- can also be installed (and built, even!) on linux, mac, or unix if so desired (requires mono or .NET core v3+)

current plans for the ui make it look similar to the openvpn UI due to the preponderance of log data on file descriptor 1

-rick

**Comment by neuroscr** [comment]
Why? we're going to replace it all with a cross-platform QT one?

**Comment by despair86** [comment]
i had started on this a while back, right around the time i came on to the project

before qt5 was decided upon

*shrugs*

**Comment by neuroscr** [comment]
I guess the question is why develop it further?

Well I would say, either take the reigns on the qt project or halt development until qt project catches up but sounds like this maybe required for basic windows functional, I guess we can review on the next call

**Comment by despair86** [comment]
landed in master not long ago, fully cross platform once coreCLR v3 gold drops, works on mono in the meantime
