### ISSUE TITLE
Make build system uses linux specific commands for installation

### ISSUE THREAD

**Issue by liilac** [loki-project/loki-network#108]
The GNU Makefile's install target has a dependency on install-setcap, which fails when unable to successfully set linux-specific capabilities on the file

**Comment by majestrate** [comment]
this shouldn't fail as it does a `which setcap && setcap ... || true` which should handle `setcap` not existing

**Comment by liilac** [comment]
This issue should be reviewed in the context of install targets/concerns being moved to cmake instead of a separate static makefile

**Comment by majestrate** [comment]
the setcap stuff was moved into cmakelists.txt and only run for linux targets so i'll mark this as resolved for now.
