### ISSUE TITLE
CMake generates targets that do not install binaries or libraries

### ISSUE THREAD

**Issue by liilac** [loki-project/loki-network#109]
Binaries are compiled but not installed.  This is the case using ninja and Unix Makefile build systems.

**Comment by majestrate** [comment]
yup we need to add targets for that in cmake

**Comment by liilac** [comment]
Updated title to reflect that libraries and headers are not installed either.  Should be fixed at the same time as binary installation.

**Comment by majestrate** [comment]
On Mon, Dec 10, 2018 at 06:23:23AM -0800, Lilac wrote:
> Updated title to reflect that libraries and headers are not installed either.  Should be fixed at the same time as binary installation.
working on this rn

**Comment by liilac** [comment]
Any update @majestrate ?

**Comment by majestrate** [comment]
i believe this was fixed and the fix is in staging branch at the very least.
