### ISSUE TITLE
Proposal for redundant introset lookups & publishes

### ISSUE THREAD

**Issue by jagerman** [loki-project/loki-network#1090]
Right now the introset lookup logic looks like this, where R are relays the client talks to and A,B,C,D,E are the 5 closest (in DHT space) routers.

Lookup:
- Choose the two closest (to the introset location) routers we're connected to; these are our relays "R"
- Ask each R to do an introset lookup
- Each R knows the closest node A that should have the record.
- R does a lookup on A, with a recursion value of 1
- If A has the introset it returns it
- If A does not have the introset, it sees the recusion value of 1 and so recurses to B.
- B replies with either the introset or a not found.

On publishing we do something similar, except that recursion is intended to distribute the introset and we don't have self recusion, so:
- ...
- A gets the introset, stores it, adds itself to the "already know it" set, then forwards this to the next closest who isn't in the "already know it" set.
- B gets it from A, adds itself to the "already know it" set, forwards to the closest not in that set, i.e. C.
- C gets it, D gets it, E gets it, at which point recursion stops.

Both of these have a single point of failure in "A": if A is unreachable then neither lookups nor publishing is going to work.

I think we need to do lookups in parallel for redundancy.

# Publishing

- Client selects two random routers, R, that it has established paths to (i.e. no need to be the closest path-connected routers)
- Sends publish introset to both R, with `recursion=2`
- Each R then builds a list of the 4 closest nodes to the introset.  (If R finds itself in this list then it stores it and just uses 3 closest in the below description)
- R relays a publish intro set to those closest 4 along with a `recursion=1`
- When a node, A, receives the publish request with `recursion==1` it checks to see if it is in the 4 closest.  If it is, it stores it and is done.
- Otherwise A, who does not see itself in the closest 4, sends it to the closest 4 with `recursion=0`.
- When a node B receives it with `recursion==0` it stores it if it thinks it is in the 4, otherwise drops it.

This gives us redundancy at multiple levels: if an R goes down, the other R works.  If any of the 4 closest aren't reachable, no big deal; the others have it.

# Lookup

- Client selects two random, R and S, that it is connected to (no need for them to be closest)
- Client initiates lookup request on each but tells R that it is in position 1, and tells S that it is in position 2.
- If a relay has the introset return it instantly.
- The relay router called in position 1 requests from the closest and 2nd closest node.
- The relay router called in position 2 requests from the 3rd closest and 4th closest node.

Thus we have a good chance of getting the record from all of the nodes that have it; if one router is out of date, not a big deal, the other should still pick it up.  If any of the top 4 is done, still not a problem.

**Comment by tewinget** [comment]
seems reasonable.

**Comment by majestrate** [comment]
a minor nitpick, clients don't use connected routers they use path endpoints.

**Comment by majestrate** [comment]
this is in 0.7.0
