### ISSUE TITLE
dns code should use llarp_buffer_t

### ISSUE THREAD

**Issue by majestrate** [loki-project/loki-network#11]
most of the dns code currently doesn't use `llarp_buffer_t` functions

just putting this here so i don't forget.

**Comment by neuroscr** [comment]
addressed in #58 we should upgrade ev* to use `llarp_buffer_t` too

**Comment by majestrate** [comment]
On Wed, Nov 21, 2018 at 05:59:26PM -0800, Ryan Tharp wrote:
> addressed in #58 we should upgrade ev* to use `llarp_buffer_t` too

yes, we should.

**Comment by neuroscr** [comment]
created a new issue #98 for the new issue, closing this one.
