### ISSUE TITLE
Error on installing in Windows

### ISSUE THREAD

**Issue by SamtheTruck** [loki-project/loki-network#1100]
I had an error on installing in Windows. I notice that the installation instructions are for windows 10 but it does speak of installing for other versions elsewhere.

1. If It won't install on windows 7 then a simple, "Can't install on Windows 7" would be nice.

2. Here's what I did. I installed NOT to the C: drive as I do not want it on C but on an encrypted drive "O:". My SSD C: drive is very small so I don't want it there and on an encrypted drive is much safer. I downloaded the file, "lokinet_windows_installer_v0.5.2.exe", and the downloaded size is 8.97MB. I noticed on the download page it said 11MB???? When run it reads "connecting" until it gets to 7z.exe then stops with http error 521. Yes I did try running it as an administrator. I don't have problems installing any other software with the same set up so....

3. I also, thinking maybe it was a WIn7 issue, tried installing an earlier version"lokinet-windows-v0-5.exe" and had the same results.

**Comment by majestrate** [comment]
On Fri, Feb 14, 2020 at 03:45:33PM -0800, SamtheTruck wrote:
> I had an error on installing in Windows. I notice that the installation instructions are for windows 10 but it does speak of installing for other versions elsewhere.
> 
> 1. If It won't install on windows 7 then a simple, "Can't install on Windows 7" would be nice.
> 
> 2. Here's what I did. I installed NOT to the C: drive as I do not want it on C but on an encrypted drive and my SSD C drive is very small. I downloaded and the file. "lokinet_windows_installer_v0.5.2.exe", size is is 8.97MB. I noticed on the download page it said 11MB???? When run it reads "connecting" until it gets to 7z.exe then stops with http error 521. Yes I did try running it as an administrator. I don't have problems installing any other software with the same set up so....

lokinet 0.5.x is not the current supported release, the binaries you have are outdated. we are planning to release a functional windows build with the next hardfork for lokinet 0.7.x

**Comment by SamtheTruck** [comment]
No trying to be a smart alek at all. I went to this page
https://loki.network/getstarted/
and downloaded from this link
https://loki.network/lokinetWindows
and got this
lokinet_windows_installer_v0.5.2.exe
???? Is the link pointing to the wrong place??? if not then some sort of warning, maybe just remove the link???

Thanks for the work on this I'm looking forward to it and the path you are choosing from the docs sounds very promising.

**Comment by majestrate** [comment]
On Fri, Feb 14, 2020 at 04:30:12PM -0800, SamtheTruck wrote:
> No trying to be a smart alek at all. I went to this page
> https://loki.network/getstarted/
> and downloaded from this link
> https://loki.network/lokinetWindows
> and got this
> lokinet_windows_installer_v0.5.2.exe
> ???? Is the link pointing to the wrong place??? if not then some sort of warning, maybe just remove the link???

it seems that the link never got updated, thanks for the report.
