### ISSUE TITLE
Allow for future use of nonService Nodes as routers

### ISSUE THREAD

**Issue by SamtheTruck** [loki-project/loki-network#1101]
Reading about the LLARP - Low Latency Anon Routing Protocol

https://github.com/loki-project/loki-network/blob/master/docs/high-level.txt

I see super great stuff. I'm in agreement and really like the path you've taken. One thing I believe would increase security is if there were a option to route through an average user just like I2P. It could be selected as an option. It would be slow but I think it would add security. I'm certainly not saying this is something needed RIGHT NOW. My purpose is that as you're writing this you don't move the code in such a way as to make this impossible. People who are really worried about security, say if you were a health worker in China reporting on the Corona virus, could exchange speed for the enhanced security that a mass amount of routers would provide. Being able to pick the amount of hops would be nice too.

I also believe that if you had a torrent, actually magnet, service with a hidden site tracking them it would immediately pick up usage of your software.

**Comment by majestrate** [comment]
you can do that right now, you just need to run a separate network with another netid without a staking requirement and it should work fine.

**Comment by jagerman** [comment]
Picking the number of hops is fine and something we can enable via a client config (up to an internal limit of 8 or 10, IIRC), but allowing unstaked routers into the router pool goes against the model here: namely it would allow someone to flood the network with new routers in the hopes of attracting (and monitoring) traffic through those routers.  Tying routers to stakes, however, means that such an attack to gain network metadata monitoring capabilities is economically prohibitive.
