### ISSUE TITLE
Configuration is poorly typed and not explicitly defined

### ISSUE THREAD

**Issue by liilac** [loki-project/loki-network#113]
The configuration is poorly typed, with all values being strings, despite several being URLs, booleans, integers, IP addresses, etc.

The configuration struct is defined as a sectioned KV map, with all values stored as strings, creating a need to later cast them to their actual types, and removing compile-time type safety.

The fact that a map is used over defined struct members makes it unnecessarily difficult to ascertain what configuration is used/required.

Is there a reason this approach was chosen over using a configuration library, or even just a YAML (my preference) or INI parsing library, with the full configuration structure defined in code?

To summarise some Discord discussion, there's a few points
* configuration is a map and not explicitly defined; hurts reasoning and readability, removes compile-time safety
* configuration values are weakly typed; creates a need to cast and removes compile-time safety
* appropriateness of using a library over custom, internally maintained, code

See [`llarp/config.hpp`](https://github.com/loki-project/loki-network/blob/master/llarp/config.hpp) and [`llarp/config.cpp`](https://github.com/loki-project/loki-network/blob/master/llarp/config.cpp) for reference.

Relevant libraries:
* [hyperrealm/libconfig](https://github.com/hyperrealm/libconfig)
* [jbeder/yaml-cpp](https://github.com/jbeder/yaml-cpp)

**Comment by neuroscr** [comment]
INI was chosen for UX. If other projects can use INI, it's probably possible somehow to make it work.

I'm against using YAML

>appropriateness of using a library over custom, internally maintained, code
This is not a value we hold. More dependencies isn't always a good thing.

Compile-time safety is your strongest point here.

**Comment by despair86** [comment]
liilac: if you want, we _could_ go full TOML (ew) to gain access to more descriptive types 🤔

**Comment by neuroscr** [comment]
At least TOML is like INI, it maybe a good compromise, if we need one
https://github.com/toml-lang/toml

**Comment by liilac** [comment]
I think it's important to clarify, my commentary was actually on the representation of the configuration in code, not in the configuration files.

@neuroscr

**Comment by liilac** [comment]
What was the reason for closing this?  Would it be possible to get a summary of the thoughts and reasoning behind a deliberate choice to not (at some point) have a well-typed representation of the configuration in code? @majestrate

**Comment by majestrate** [comment]
On Tue, Apr 16, 2019 at 12:39:20AM -0700, Lilac wrote:
> What was the reason for closing this?  Would it be possible to get a summary of the thoughts and reasoning behind a deliberate choice to not (at some point) have a well-typed representation of the configuration in code? @majestrate 
ini files are probably the simplest config format for end users, having anything more intricate will probably screw with less skilled users.

**Comment by liilac** [comment]
@majestrate I think you're misunderstanding the proposal here.

It's nothing to do with the configuration file format; comments on changes to that were tangential.

The proposal and discussion here (on my part), was about having a well-typed representation of the configuration in code; i.e. with structs and such.

Simplistic example in plain C:
```c
typedef struct
{
    int listenPort;
    const char* nickname;
    // ...
} config;
```

**Comment by majestrate** [comment]
ah i see, that would make more sense.

**Comment by liilac** [comment]
Might be helpful to link an exhaustive sample config here

**Comment by majestrate** [comment]
the sample config is generated by lokinet using the `-g` flag

**Comment by majestrate** [comment]
we have refactored the config layer to make things more strongly typed.
