### ISSUE TITLE
can't connect to lokinet wiki

### ISSUE THREAD

**Issue by unmellow** [loki-project/loki-network#1169]
**Describe the bug**
when i try to connect to the lokinet wiki the server isn't found also
also lokinet says "failed to handle hooked dns"

**To Reproduce**
login to shell on tty 2 and start lokinet
login to gnome wayland from gdm
attempt conection to http://wikicymsw5cy1h367oo9wwxuhp7igcrxcugy6kn4h5kgdzmq8qho.loki/wiki/
found [here](http://www.wikicymsw5cy1h367oo9wwxuhp7igcrxcugy6kn4h5kgdzmq8qho.loki/wiki/)

**Screenshots Or Logs**
![Screenshot from 2020-03-07 11-19-10](https://user-images.githubusercontent.com/30985587/76146932-8787aa80-6065-11ea-9aed-ee90cdee6023.png)
)

**Device and Operating system (please complete the following information):**
 - OS: [manjaro linuc clearos kernel]
-  Device: [ custom (ryzen 5 gigabyte etc)]
 - Lokinet Version number or Git commit hash:up to date as of post (how do i get ether of these?)

**Comment by majestrate** [comment]
the wiki is at http://dw68y1xhptqbhcm5s8aaaip6dbopykagig5q5u1za4c7pzxto77y.loki/ right now, there was a key format shift and we haven't updated the docs yet.

**Comment by unmellow** [comment]
that link works thank you!

**Comment by majestrate** [comment]
which docs were you using?

**Comment by unmellow** [comment]
https://docs.loki.network/Lokinet/Guides/AccessingSNApps/
i can get there from here https://lokinet.org/ and here https://loki.network/

**Comment by majestrate** [comment]
looks like the docs got updated.

**Comment by justhx0r** [comment]
Anyone knowing who runs that server?
Looks like they misconfigured their nginx...
