### ISSUE TITLE
Website needs to be updated

### ISSUE THREAD

**Issue by danrobi11** [loki-project/loki-network#1185]
Hi
Tried open issue here: https://github.com/loki-project/lokinet-site
But it wont let me so I came here.
Users cant use lokinet from bad docu. Plz update ASAP! https://docs.loki.network/Lokinet/Guides/PublicTestingGuide/#2-accessing-snapps
This should be provided to the users:
irc://dw68y1xhptqbhcm5s8aaaip6dbopykagig5q5u1za4c7pzxto77y.loki/lokinet
http://dw68y1xhptqbhcm5s8aaaip6dbopykagig5q5u1za4c7pzxto77y.loki/
http://zhrxg3kuc59g85k9xrih71t9tn7dp7ysd7bfgzfww1dnqcirq75y.loki/

Thanks!

**Comment by majestrate** [comment]
moved to the correct repo.
