### ISSUE TITLE
codel vs fq_codel, target's for 200ms?

### ISSUE THREAD

**Issue by dtaht** [loki-project/loki-network#12]
I have not the foggiest idea what you are attempting to do with this project, but I happened to see commit 3dbe3f8d9721eb321455ff5241c1c0d2858c8c46 go by which fiddled with codel's parameters hugely. My assumption (having issues with parsing your C++ code generally) is that the typical RTT in your overlay network is in the 200ms? range?, in which case your codel target should be in the 10ms range, and interval 200ms. 

Also, if at all possible at these crypto layers, fq_codel tends to work a lot better than pure codel. Interleaving different flows over an RTT really helps.

**Comment by majestrate** [comment]
Thanks for the input, I was faced with picking a congestion control algorithm and ended up trying to implement codel but probably screwed it up.

**Comment by majestrate** [comment]
i am unsure if fq_codel applies at the level i use it at right now, but some future parts of the code would be best to use fq_codel since it can differentiate between flows on the upper layers.

**Comment by dtaht** [comment]
one thing we do with fq_codel nowadays is preserve the inner hash of the original headers (hash is seeded with a random number but doesn't presently rotate), before it hits the vpn. At one level this improves entropy, at another it might be an info leak. I do know that torrent over tcp sucks due to lousy congestion control. 

I'll try to parse your implementation over the weekend. I am terrible at c++ though.

**Comment by majestrate** [comment]
I do suspect that the initial congestion control, latency and jitter for lokinet will suck pretty hard. I am unsure how much as i have yet to take any real world measurements on such being stuck in pumping out the gutts of it all. i believe we hope to launch a demo in about 2 months so I have been grinding hard since mid may.

**Comment by majestrate** [comment]
this is because of using many short segments instead of it being a continuous bulk transfer right?

**Comment by majestrate** [comment]
update: the last part of the code that still uses CoDel is the ip interface used to send packets over the network and the os could be able to handle that itself with its own stuff. not sure where i'd be able to use CoDel as of right now that would make sense besides maybe for limiting path and inter path traffic.

I'll mark this as closed for now.
