### ISSUE TITLE
Crash on start with hidden service

### ISSUE THREAD

**Issue by noalphakamp** [loki-project/loki-network#121]
[ERR] unnamed (728) Mon Dec 10 09:40:36 2018 EST llarp/service.cpp:207  bdecode buffer size missmatch 3200!=2818 
[WRN] unnamed (728) Mon Dec 10 09:40:36 2018 EST llarp/BEncode.hpp:66   failed to decode key q for entry in dict 
[ERR] unnamed (728) Mon Dec 10 09:40:36 2018 EST llarp/dht.cpp:263      unhandled key 'q'                        
[ERR] unnamed (728) Mon Dec 10 09:40:36 2018 EST llarp/service/context.cpp:200  derp failed to start             
[ERR] unnamed (728) Mon Dec 10 09:40:36 2018 EST llarp/router.cpp:921   Failed to start hidden service context

**Comment by neuroscr** [comment]
Can confirm happening to me too
