### ISSUE TITLE
Make repo popular

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#122]
We need watchers, stars and forks!

Goal
30 forks, 30 watchers and 75 stars (to be added to homebrew)

Post any ideas for making this happen.

**Comment by majestrate** [comment]
On Mon, Dec 10, 2018 at 07:01:41PM +0000, Ryan Tharp wrote:
> We need watchers, stars and forks!

I mean we don't NEED homebrew quite yet as it's mostly a nice to have gimmick for attracting
additional attention, if we don't have enough right now to qualify that's probably fine.

I hope this doesn't mean we suddenly get mass media news coverage or stuff. ;~;
