### ISSUE TITLE
GUI doesn't scale well on a 4k monitor 

### ISSUE THREAD

**Issue by Lucifer1903** [loki-project/loki-network#1220]
**Describe the bug**
GUI doesn't scale well on 4K

**To Reproduce**
Use a 4K monitor. 

**Screenshots Or Logs**
![DSC_3111](https://user-images.githubusercontent.com/29006257/79019001-2aec4380-7b6d-11ea-9f08-7ddf86ae9463.JPG)

**Device and Operating system (please complete the following information):**
 - OS: Windows 10
 - Lokinet Version 0.7.0

**Comment by despair86** [comment]
ohh

i set my 4K panel to 96 ppi, need a microscope to read stuff on it

**Comment by majestrate** [comment]
wow, that's freaking awesome.

**Comment by notlesh** [comment]
Lol.

This isn't just simply running on a 4k monitor -- I've done that on all OSes that we support. It must be the OS and/or Qt trying to do some scaling.

What do you have your monitor's scale set to?

**Comment by despair86** [comment]
125-150% methinks

**Comment by Lucifer1903** [comment]
It's set to 300%. Strange I can't see the photo I uploaded.

**Comment by jagerman** [comment]
> Strange I can't see the photo I uploaded.

I had trouble with it too.  Now that MS owns github they are probably putting all their servers on Windows so we are getting the rock solid reliability that Windows is known for.

**Comment by notlesh** [comment]
> > Strange I can't see the photo I uploaded.
> 
> I had trouble with it too. Now that MS owns github they are probably putting all their servers on Windows so we are getting the rock solid reliability that Windows is known for.

It's probably WSL Enterprise Edition running under Windows Server 2021.

**Comment by majestrate** [comment]
this is an issue for https://github.com/loki-project/loki-network-control-panel
