### ISSUE TITLE
Move libcurl & libuv downloading into CMake

### ISSUE THREAD

**Issue by jagerman** [loki-project/loki-network#1230]
We already do the build inside cmake, it should be pretty easy to do the downloading there as well (like we do for sodium).  Currently the downloading is in the Makefile and the building is in the CMakeLists.txt.

**Comment by jagerman** [comment]
Actually: when we download libuv we already do it via git submodule; we should just put a submodule in `external` for it.

**Comment by despair86** [comment]
only do it if we can't find libuv and `LIBUV_ROOT` isn't specified

**Comment by despair86** [comment]
libcurl isn't even required on windows

**Comment by majestrate** [comment]
yeah i'd like libuv to be a submodule so that we can use the revision that has shadow related fixes.

**Comment by despair86** [comment]
> shadow
you still use that? O_O
