### ISSUE TITLE
MacOS GUI doesn't scale and is oversized on 13" macbook pro

### ISSUE THREAD

**Issue by yidakee** [loki-project/loki-network#1244]
.As per title, lower end of the GUI gets buried under the launchpad bar

MacOS 10.14.16
Late 2013 13" Mackbook Pro
Lokinet 0.7.1

<img width="400" alt="Screenshot 2020-04-24 at 14 57 12" src="https://user-images.githubusercontent.com/16577836/80221049-a0abe100-863c-11ea-944b-6048513c1970.png">

**Comment by majestrate** [comment]
can you make an issue on https://github.com/loki-project/loki-network-control-panel ?

**Comment by majestrate** [comment]
this is an issue for https://github.com/loki-project/loki-network-control-panel
closing for now, please remake it on that repo. thnx.
