### ISSUE TITLE
lokinet should issue ICMP rejections for unmapped addresses

### ISSUE THREAD

**Issue by cathugger** [loki-project/loki-network#1271]
I asked jeff about it and apparently lokinet doesn't issue any kind of rejections for packets without any mapped addresses.
This behavior (essentially silent DROP) is potentially harmful as existing connections to these addresses won't be killed and stall (for example after lokinet client restart), and even worse it could lead to packets of old connections getting misdirected to different peers, if new address gets mapped to that IP slot.
looking at https://www.iana.org/assignments/icmp-parameters/icmp-parameters.xhtml#icmp-parameters-codes-3 we should probably be using code 7 "Destination Host Unknown" or code 1 "Host Unreachable".
according to https://tools.ietf.org/html/rfc1122#page-39 code 7 is more definitive, while 1 can be interpreted only as hint, not proof. I don't know what's exactly the difference of handling of them in operating systems. Behavior should probably be tested (does any of them get cached by OS? that'd be potentially bad, but could be worked around if known).
cc @majestrate

**Comment by majestrate** [comment]
added in https://github.com/loki-project/loki-network/pull/1272/commits/fdb7547de80dfa87ae21919b0ca8269413842a3d which is a part of #1272

**Comment by majestrate** [comment]
was merged into dev
