### ISSUE TITLE
Bencode formats

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#130]
Missing keys should be FATAL

Extra keys (possible old format that's now deprecated) should be a WARN

**Comment by majestrate** [comment]
ideally we need to implement seek/discard of entities instead of just hard failing if they are not the expected format.

**Comment by majestrate** [comment]
idea, have `llarp::IBEncodeMessage` have a member for unrecondised values

**Comment by majestrate** [comment]
it's not, it's a `llarp_buffer_t` which is a pointer to a region of memory, it doesn't copy it.

**Comment by majestrate** [comment]
oh, right, it's for older version to not die when parsing newer messages

**Comment by neuroscr** [comment]
closing because no one cares any more
