### ISSUE TITLE
Cannot use LokiNet with a VPN

### ISSUE THREAD

**Issue by FireMasterK** [loki-project/loki-network#1313]
**Describe the bug**
When I use LokiNet with a VPN, I am unable to ping lokinet addresses but when I turn my VPN off, I'm able to access lokinet sites.

**To Reproduce**
Connect to a VPN (used Mullvad in this case)
Turn on LokiNet
Try pinging your own LokiNet address.

**Screenshots Or Logs**
If applicable, add screenshots or log files to help explain your problem.
![image](https://user-images.githubusercontent.com/20838718/85930854-47cb2400-b8dd-11ea-9b41-ea5e07b5c980.png)

**Device and Operating system (please complete the following information):**
 - OS: Windows
-  Device: Desktop
 - Lokinet Version number or Git commit hash: v0.7.1

**Comment by majestrate** [comment]
lokinet does not play nice with (other) VPN tunnels because it is itself a VPN tunnel.
i don't think we can automagic every single edge case that is caused by using (another) VPN with lokinet.

**Comment by FireMasterK** [comment]
Why close this? Could a solution be to use `WinDivert` if running on Windows? `Windivert` works with VPNs from my experience.

**Comment by majestrate** [comment]
the problem in this case is that mullvad VPN overrides DNS settings that lokinet uses. in general using lokinet with another VPN is a can of worms I don't want to support as it's not worth the trouble. In addition we are building something objectively better than a single hop VPN so I really don't care if they aren't supported with lokinet.
