### ISSUE TITLE
failed to bind jsonrpc to 127.0.0.1:1190

### ISSUE THREAD

**Issue by nolyoi** [loki-project/loki-network#1316]
**Describe the bug**
`[ERR] [lokinet](383) 2020-07-19 18:30:42.376 UTC [+33.013s] router/router.cpp:923	failed to bind jsonrpc to 127.0.0.1:1190`

**To Reproduce**
Followed install instructions on Github. Added the nameserver to resolv conf as well.

**Screenshots Or Logs**
![image](https://user-images.githubusercontent.com/59351042/87882220-45cc2080-c9c4-11ea-8740-e9e8bc8975b1.png)

**Device and Operating system (please complete the following information):**
 - OS: Pop_OS 20.04/Ubuntu 20.04
 - Lokinet Version number or Git commit hash:  0.7.1

**Comment by majestrate** [comment]
lokinet doesn't need to run in the foreground it's started as a service and runs in the background by default.

**Comment by nolyoi** [comment]
> lokinet doesn't need to run in the foreground it's started as a service and runs in the background by default.

Doesn't seem to run at all. I can't access .Loki addresses or anything.  GUI or cli. I've added nameservers too.

**Comment by jagerman** [comment]
It's possible something else on your system is already listening on that port and thus conflicting.  If so, this ought to tell you what it is:

`sudo netstat -lntp | grep :1190`

**Comment by majestrate** [comment]
this was fixed when moving to lmq
