### ISSUE TITLE
FR/Question: connect snapp to loki network without connecting whole computer to loki network

### ISSUE THREAD

**Issue by ITwrx** [loki-project/loki-network#1338]
this may be a stupid question, but i see the loki connecting app as the only mentioned way to connect to the loki network, and i was wondering if it's already possible to just connect a snapp to the network instead of the whole OSes network connection, and it's just not documented, or i didn't find the docs, or it's not implemented yet?
thanks

**Comment by majestrate** [comment]
I was thinking of having lokinet attach the tun interface to a networking user namespace but i never was allocated time for that. I still want to do that, but for now run them inside of an lxc if you want isolation.

**Comment by majestrate** [comment]
also a lxc config snippet i use to make containers like tun interfaces:

```
lxc.cgroup.devices.allow = c 10:200 rwm
lxc.mount.entry = /dev/net dev/net none bind,create=dir 0 0
```

**Comment by ITwrx** [comment]
ahh yes,. i might use systemd containers for that too, i bet. thanks for the snippet too.

**Comment by majestrate** [comment]
if you get systemd containers working any insights on getting that working would be quite useful. i think we could maybe use them in the debs to make some tasks easier.

**Comment by ITwrx** [comment]
it may be a while before i get to this project and depending on language and structure decided on, maybe even longer to get anything accomplished, but i'll surely do that.

**Comment by ITwrx** [comment]
and i'm currently using fedora so i'll have to be able to build loki stuff on fedora at some point.

p.s. i'll let y'all decide when to close this issue.
