### ISSUE TITLE
Make peerdb logging less verbose

### ISSUE THREAD

**Issue by jagerman** [loki-project/loki-network#1361]
Currently my lokinet client logs are 90% these three lines repeating every 30s:

Sep 22 17:45:04 betwixt lokinet[92017]: [WRN] [](969) 2020-09-22 20:45:04.225 GMT [+31.029s] router/router.cpp:863	Queing database flush...
Sep 22 17:45:04 betwixt lokinet[92017]: [NFO] [](738) 2020-09-22 20:45:04.225 GMT [+31.029s] peerstats/peer_db.cpp:83	Updating 4 stats
Sep 22 17:45:04 betwixt lokinet[92017]: [NFO] [](738) 2020-09-22 20:45:04.227 GMT [+31.031s] peerstats/peer_db.cpp:99	PeerDb flush took about 0.002s seconds

I think we can probably demote all of that to debug level.

**Comment by majestrate** [comment]
this has been rectified
