### ISSUE TITLE
Lokinet slows clearnet traffic

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-network#139]
When Lokinet is turned on clearnet traffic significantly slows, i assume this is to do with Lokinet attempting to handle the DNS resolution for clearnet addresses.

Once exits are implemented this process will need to occur, but as of right now is there an easy way for lokinet to quickly reject all clearnet addresses and send those address to the secondary DNS resolver (is this what caused the additional latency already?). I think this feature would be valuable even when we do have full exit functionality, it could be used for people who only want only .loki addresses to be resolved by lokinet.

**Comment by majestrate** [comment]
On Tue, Dec 11, 2018 at 08:33:57PM -0800, Kee Jefferys wrote:
> When Lokinet is turned on clearnet traffic significantly slows, i assume this is to do with Lokinet attempting to handle the DNS resolution for clearnet addresses.
it may be because of the dns resolvers chosen in defaults, suggestion: try only using 1.1.1.1 as upstream dns resolver in lokinet.ini
> 
> Once exits are implemented this process will need to occur, but as of right now is there an easy way for lokinet to quickly reject all clearnet addresses and send those address to the secondary DNS resolver (is this what caused the additional latency already?). I think this feature would be valuable even when we do have full exit functionality, it could be used for people who only want only .loki addresses to be resolved by lokinet.
exits are implemented and have been for quite some time.

**Comment by KeeJef** [comment]
Related https://github.com/loki-project/loki-network/pull/150

**Comment by majestrate** [comment]
On Fri, Dec 14, 2018 at 12:17:52AM -0800, Kee Jefferys wrote:
> Related https://github.com/loki-project/loki-network/pull/150
merged
