### ISSUE TITLE
Testnet isolation

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#161]
Can we make something we can set to keep one lokinet testnet from merging with another?

This may help from accidentally blowing up our nodedbs

**Comment by majestrate** [comment]
On Mon, Dec 17, 2018 at 03:56:35PM -0800, Ryan Tharp wrote:
> Can we make something we can set to keep one lokinet testnet from merging with another?
> 
> This may help from accidentally blowing up our nodedbs
put your bootstrap node on a web server i.e. at https://bootstrap.lokinet.org/bootstrap.signed

then to bootstrap the test network run

lokinet-bootstrap https://bootstrap.lokinet.org/bootstrap.signed

**Comment by neuroscr** [comment]
yea, I know. And that's also (possibly) broken but not what this ticket is about. I'm talking about taking isolation a step further, so they can't intermingle and merge and have to change port

**Comment by majestrate** [comment]
fixed in staging, but needs to be configurable on runtime.

**Comment by majestrate** [comment]
now configurable on runtime via `[router]` section `netid=toastnet`, the value of `netid` must be 8 bytes or less
