### ISSUE TITLE
Testnet bootstrapping

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#163]
A reminder for me, so I can fix loki-messengers testnet

**Comment by majestrate** [comment]
you can use an alternative bootstrap node as parameter `lokinet-bootstrap http://other.server.tld/whatever.signed` which should be used in the event of a test network

**Comment by neuroscr** [comment]
yea, we got the seed but can't get past:
`Not enough dht nodes, have 0 want 1`
even though we've added 4 nodes in [connect] on loki5 (4 outgoing)
and all 5 routers have loki1 as the seed (4 incoming)

**Comment by majestrate** [comment]
when running a testnet make sure to enable network segmentation configurable via `[router]` via `netid` value

**Comment by neuroscr** [comment]
I had modified the wanted DHT nodes to be more dynamic. I'm going to close this issue out
