### ISSUE TITLE
Add more Success messages

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-network#164]
Add a success messages after the Bootstrap and Config generation 

```
$ lokinet -r -g
$ lokinet-bootstrap 
```

**Comment by majestrate** [comment]
`lokinet` already says it generated a config file if it does otherwise it's silent

`lokinet-bootstrap` reports error but otherwise is silent.

**Comment by KeeJef** [comment]
lokinet-bootstrap, should report success as of this commit https://github.com/loki-project/loki-network/commit/faad5a66d6bc305fc3ed065aa376c9b0b4ee1ac5

**Comment by despair86** [comment]
the Windows package runs this *only* at installation, only people who compile from source would have a persistent copy of bootstrap on Windows

**Comment by KeeJef** [comment]
Closing this now that this is in https://github.com/loki-project/loki-network/commit/611c166c062bcd11026336785627fa236d357ed0 

Seems it is unnecessary to add success messages for the config generations
