### ISSUE TITLE
Error messages when closing Lokinet

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-network#168]
When i send the message to kill Lokinet (Ctrl + c) it exits with the same set error messages each time

> ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408       sendto failed: Bad file descriptor
[ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408 sendto failed: Bad file descriptor
[ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408 sendto failed: Bad file descriptor
[ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408 sendto failed: Bad file descriptor
[ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408 sendto failed: Bad file descriptor
[ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408 sendto failed: Bad file descriptor
[ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408 sendto failed: Bad file descriptor
[ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408 sendto failed: Bad file descriptor
[ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408 sendto failed: Bad file descriptor
[ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408 sendto failed: Bad file descriptor
[ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408 sendto failed: Bad file descriptor
[ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408 sendto failed: Bad file descriptor
[ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408 sendto failed: Bad file descriptor

Also should there be some sort of graceful exit strategy?

**Comment by majestrate** [comment]
On Wed, Dec 19, 2018 at 09:14:16PM -0800, Kee Jefferys wrote:
> When i send the message to kill Lokinet (Ctrl + c) it exits with the same set error messages each time
> 
> > ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408       sendto failed: Bad file descriptor
> [ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408 sendto failed: Bad file descriptor
> [ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408 sendto failed: Bad file descriptor
> [ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408 sendto failed: Bad file descriptor
> [ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408 sendto failed: Bad file descriptor
> [ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408 sendto failed: Bad file descriptor
> [ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408 sendto failed: Bad file descriptor
> [ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408 sendto failed: Bad file descriptor
> [ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408 sendto failed: Bad file descriptor
> [ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408 sendto failed: Bad file descriptor
> [ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408 sendto failed: Bad file descriptor
> [ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408 sendto failed: Bad file descriptor
> [ERR] unnamed (329) Thu Dec 20 06:09:05 2018 CET llarp/link/utp.cpp:408 sendto failed: Bad file descriptor

that is probably because the udp socket closes before the utp sessions have time to send their close packet.

this is bug in shutdown order.

**Comment by majestrate** [comment]
this should be fixed in master
