### ISSUE TITLE
Dump lokinet address in file

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-network#169]
Right now to setup a loki SNApp you need to get your .loki address by reading through the initial console output. To make the user experience cleaner i think we should dump the users SNApp public key to file, unencoded. This would match the Tor hidden service setup UX, which dumps a file for your hidden service hostname. 

> The other file Tor will create is called "hostname". This contains a short summary of your public key -- it will look something like duskgytldkxiuqc6.onion. This is the public name for your service, and you can tell it to people, publish it on websites, put it on business cards, etc.

**Comment by majestrate** [comment]
On Wed, Dec 19, 2018 at 10:07:39PM -0800, Kee Jefferys wrote:
> Right now to setup a loki SNApp you need to get your .loki address by reading through the initial console output. To make the user experience cleaner i think we should dump the users SNApp public key to file, unencoded. This would match the Tor hidden service setup UX, which dumps a file for your hidden service hostname. 
yup i agree that is a good idea.
i think we can make that configurable but with some sane defaults

**Comment by KeeJef** [comment]
we should just dump the public key to the same path as specified with
`keyfile=`
then when a user sets up their SNApp they have all the keys in the same location, nice and easy

**Comment by neuroscr** [comment]
we have too many configureable filenames. I think the keyfile filename should be the base32z .loki address plus some suffix like ".hiddenservice_key" or ".snapp_key". And then we don't have to change on disk format

**Comment by despair86** [comment]
seconded

was musing about combining the existing keychain (from separate files `self.signed`, `*.private`) into a single `[base32].loki_keys` file, then using some kind of delimiter to split the file back into its component parts when loaded into core

**Comment by neuroscr** [comment]
hrm it's a chicken/egg problem, you don't know if you should create a file without a filename given, if you give a filename then you know the address, before you make it.

So still thinking on this.

**Comment by majestrate** [comment]
what if we dump settings as json to a file? (including loki address, interface address and other options)

**Comment by majestrate** [comment]
i have a way to do this now in my local branch. will merge it this week.

**Comment by majestrate** [comment]
how to:

make `/usr/local/lokinet-on-up.sh` with the contents:

```
#!/usr/bin/env bash
echo "$LOKINET_ADDR" > "$1"
```

then `chmod +x /usr/local/lokinet-on-up.sh`

lastly in network section:

```
on-up=/usr/local/lokinet-on-up.sh /path/to/hostfile
```

**Comment by majestrate** [comment]
please note that win32 is not supported yet

**Comment by necro-nemesis** [comment]
Should just script the whole SNapp creation process using this info leaving the user with where to place the index file and what the address is.

**Comment by majestrate** [comment]
On Tue, May 07, 2019 at 03:12:15PM +0000, necro-nemesis wrote:
> Should just script the whole SNapp creation process using this info leaving the user with where to place the index file and what the address is.
care to expand on this?

**Comment by necro-nemesis** [comment]
Pretty much everything that is posted on the guide to initiate hosting a SNapp is gathering info from the system, writing an entry to lokinet.ini or creating a file from the pubkey info. A little script could do all that if say /snapp/index.html is standardized as the default SNapp directory. The script could even make a little default index.html to test it out like "Hello from $USER".

**Comment by majestrate** [comment]
i have a script to redirect all traffic over lokinet and poke holes into the routing table

my config:
```
...
[network]
strict-connect=myfirsthophere.snode
strict-connect=anotherfirsthophere.snode
exit-node=myexitnode.snode
on-up=/home/jeff/.lokinet/on-up.sh
on-down=/home/jeff/.lokinet/on-down.sh
on-ready=/home/jeff/.lokinet/on-ready.sh booyeah
```

`$HOME/.lokinet/on-down.sh`

```
#!/usr/bin/env bash
# this will be overriden by on-up.sh
```

`$HOME/.lokinet/on-up.sh`
```
#!/usr/bin/env bash
set -x
gateway_route=$(ip route | grep ^default | grep via | head -n1)
gateway_addr=$(echo "$gateway_route" | cut -d' ' -f3 )
for addr in $STRICT_CONNECT_ADDRS ; do
        sudo ip route add $(echo $addr | cut -d':' -f 1) via $gateway_addr
done
sudo ip route del $gateway_route                                                                                                                                                                                                                                                                                                                                                                                                         
sudo ip route add default dev lokitun0
cat <<EOF > $HOME/.lokinet/on-down.sh
#!/usr/bin/env bash
set -x
for addr in \$STRICT_CONNECT_ADDRS ; do
        sudo ip route del \$(echo \$addr | cut -d':' -f 1) via $gateway_addr
done
sudo ip route del default dev lokitun0
sudo ip route add $gateway_route

EOF
chmod +x $HOME/.lokinet/on-down.sh
```

`$HOME/.lokinet/on-ready.sh`

```
#!/usr/bin/env bash
notify-send "$@ Our Loki Address $LOKINET_ADDR is ready on address $IF_ADDR on $IF_NAME"
```


add to `/etc/sudoers`:

`%sudo ALL = NOPASSWD: /sbin/ip`

**Comment by necro-nemesis** [comment]
Ok I'll work on adding that to the AP code. Should it be a selection i.e. able to enable/disable or just go at it head first and make it the standard operation?

Those two first hops? What's going on there for fetching addresses?

**Comment by majestrate** [comment]
On Tue, May 07, 2019 at 12:56:07PM -0700, necro-nemesis wrote:
> Ok I'll work on adding that to the AP code. Should it be a selection i.e. able to enable/disable or just go at it head first and make it the standard operation?
> 
no idea, you tell me.

> Those two first hops? What's going on there for fetching addresses?
those snode addreses are placeholder values

**Comment by necro-nemesis** [comment]
undecided if I want to patch lokinet.ini or just replace the config with the added entries.

**Comment by necro-nemesis** [comment]
I kind of an all or none guy in my application. If you want Lokinet connect to the device. If you want vanilla internet connect to whatever million other devices serve that up is my thinking.

**Comment by necro-nemesis** [comment]
I'm just going to jamb the code in and have the option to make it selectable afterward with a button enable/disable if that seems the way to go in future.

**Comment by necro-nemesis** [comment]
```add to /etc/sudoers:

%sudo ALL = NOPASSWD: /sbin/ip```

Does this need a wildcard? i.e. %sudo ALL = NOPASSWD: /sbin/ip*

**Comment by necro-nemesis** [comment]
I'm thinking line 259 requires the wildcard.

https://github.com/necro-nemesis/Lokiap-webgui/commit/b86bd92e5d152590ec6605835552f540621b8b28

**Comment by majestrate** [comment]
no wildcard

**Comment by necro-nemesis** [comment]
ok. Any input on viable .snodes to use att?
