### ISSUE TITLE
Consensus needed on location of cmake toolchain files

### ISSUE THREAD

**Issue by liilac** [loki-project/loki-network#177]
This issue is to track verbal discussions on the topic

An issue for mobile darwin builds at least (iOS, and possibly at some point if the APIs are extended to tvOS for example), and indirectly non-mobile darwin (macOS), at the very least.

It's presently undecided where these should be located.

**Comment by majestrate** [comment]
we have decide they go at contrib/cross/whatever-toolchain.cmake
