### ISSUE TITLE
Allow RC to be signed with a custom address

### ISSUE THREAD

**Issue by kingsley22** [loki-project/loki-network#2]
Let RC be signed with a custom IP Address

**Comment by majestrate** [comment]
is this working yet?

**Comment by neuroscr** [comment]
`public-addresss` and `public-port` are working, however due to my double NAT set up, I haven't been able to successfully test it. Still working on this.

**Comment by neuroscr** [comment]
Finally was able to confirm it works. But you can't disable the private interfaces (so only my fork works atm until Jeff pulls my change/reverts his)

**Comment by majestrate** [comment]
this seems to work now as of the latest commits
