### ISSUE TITLE
If curl is not installed does not return correct error message when lokinet-bootstrap is run

### ISSUE THREAD

**Issue by Sonofotis** [loki-project/loki-network#201]
**Issue:**
If curl is not installed line 25 in `lokinet-bootstrap` does not return a correct error message.
```
curl "$url" > $HOME/.lokinet/bootstrap.signed; echo -e "${GREEN}lokinet successfully bootstrapped${NC}" || echo -e "${RED}failed to download bootstrap from $url${NC}"
```

Right hand side will only run if the left hand side exit status is non zero.

**Command ran and error message:**
```
modeify@modeify-VirtualBox:~/loki-network$ lokinet -g && lokinet-bootstrap
downloading https://i2p.rocks/i2procks.signed
/usr/local/bin/lokinet-bootstrap: line 25: curl: command not found
lokinet successfully bootstrapped
```
**Additional**
Command `lokinet-bootstrap` creates an empty file at `$HOME/.lokinet/bootstrap.signed` if curl is not installed.

**Comment by majestrate** [comment]
alright, switched to curl
