### ISSUE TITLE
Looking up random.snode in nodejs needs periodic dns flush

### ISSUE THREAD

**Issue by sachaaaaa** [loki-project/loki-network#205]
In nodejs, I am using the dns package to lookup `random.snode`:
```js
const dns = require('dns');
dns.lookup('random.snode', {}, (error, ip) => {
  ...
});
```
This will work for a few calls then stop working:
```
error: getaddrinfo ENOTFOUND random.snode
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
```
At this point, `nslookup random.snode 127.0.0.1` in my terminal still works.

I noticed that flushing the cache with `sudo killall -HUP mDNSResponder` will make the nodejs script work again immediately.

Notes: Apparently, adding `dns.setServers(['127.0.0.1'])` does not change anything to my results.
On mac OSX 10.13.6 High Sierra.

**Comment by majestrate** [comment]
you want to use `dns.resolve` not `dns.lookup` as `resolve` does not cache.

**Comment by sachaaaaa** [comment]
Unfortunately, I have never been able to get any of those `resolve` function work with 'randon.snode'.
Here's a snippet I'm running:
```js
const dns = require('dns');
const http = require('http');

const hostname = 'random.snode';
const servers = ['127.0.0.1'];

function printResults(name, err, result) {
  if (err) console.error(`${name}: threw ${err}`);
  else console.log(`${name}: returned '${result}'`);
}

dns.setServers(servers);
dns.lookup(hostname, {}, (err, ip) => {
  printResults('dns.lookup', err, ip);
});
dns.resolve4(hostname, (err, ip) => {
  printResults('dns.resolve4', err, ip);
});
dns.resolveAny(hostname, (err, any) => {
  printResults('dns.resolveAny', err, any);
});
dns.resolveCname(hostname, (err, cname) => {
  printResults('dns.resolveCname', err, cname);
});

const resolver = new dns.Resolver();
resolver.setServers(servers);
resolver.resolve4(hostname, (err, ip) => {
  printResults('resolver.resolve4', err, ip);
});
resolver.resolveAny(hostname, (err, any) => {
  printResults('resolver.resolveAny', err, any);
});
resolver.resolveCname(hostname, (err, cname) => {
  printResults('resolver.resolveCname', err, cname);
});
```
Which prints, when working:
```
dns.lookup: returned '10.200.0.5'
dns.resolve4: returned ''
dns.resolveAny: returned ''
dns.resolveCname: returned ''
resolver.resolve4: returned ''
resolver.resolveAny: returned ''
resolver.resolveCname: returned ''
```
And indeed, the ip returned by `dns.lookup` seems to be cached as it returns the same value as long as it doesn't error.
And after about 15 seconds after the first successful call:
```
dns.resolve4: returned ''
dns.resolveAny: returned ''
dns.resolveCname: returned ''
resolver.resolve4: returned ''
resolver.resolveAny: returned ''
resolver.resolveCname: returned ''
dns.lookup: threw Error: getaddrinfo ENOTFOUND random.snode
```
I am not familiar enough with how dns works, but reading from the docs, it looks like calling `dns.resolve` actually queries the network. Maybe this reaches yet-to-be-implemented territories of lokinet?
> These functions are implemented quite differently than dns.lookup(). They do not use getaddrinfo(3) and they always perform a DNS query on the network. This network communication is always done asynchronously, and does not use libuv's threadpool.
As a result, these functions cannot have the same negative impact on other processing that happens on libuv's threadpool that dns.lookup() can have.
They do not use the same set of configuration files than what dns.lookup() uses. For instance, they do not use the configuration from /etc/hosts.

Also, Ideally it would be nice to have lokinet DNS server as default system-wise, that way the Snapps don't have to explicitly know on which ip the lokinet DNS is bound to. In my case, I could just use `dns.lookup` instead of the `dns.resolve` functions.

**Comment by majestrate** [comment]
i have a fix inbound so the following code will work
```
// snode dns test script

const http = require('http');
const dns = require('dns');

// TODO: pick dns for linux too
dns.setServers(['127.0.0.1']);

/**
   resolve a random service node and call handler(err, ip)
 */
const resolveRandomSN = function(handler) {
  /* resolve random snode */
  dns.resolve('random.snode', 'CNAME', function(err, addrs) {
    if(err)
    {
      handler(err, null);
      return;
    }
    const snode = addrs[0];
    /* resolve snode address */
    dns.resolve(snode, 'A', function(err, ip) {
      if(err)
      {
        handler(err, null);
        return;
      }
      const ipaddr = ip[0];
      /** sanity check */
      dns.reverse(ipaddr, function(err, addr) {
        if(err)
        {
          handler(err, null);
          return;
        }
        if (addr == snode)
        {
          handler(null, ipaddr);
        }
        else
        {
          handler("forward and reverse dns do not match", null);
        }
      });
    });
  });
};
  
```

**Comment by sachaaaaa** [comment]
I confirm #205 (with #212) fixed this issue.
It even seems to work without `dns.setServers(['127.0.0.1']);` which is nice!
Thank you @majestrate !
