### ISSUE TITLE
add localhost.loki to resolve to all IPs owned by lokinet daemon

### ISSUE THREAD

**Issue by majestrate** [loki-project/loki-network#226]

**Comment by neuroscr** [comment]
Beaudan was talking about using this for the messenger clients to advertise their connection information on the network

**Comment by neuroscr** [comment]
so you'll return multiple A records. We may want to include some TXT records to indicate which ones are ephemeral (default) and which ones aren't (HS, hidden (non-published) HS)

**Comment by majestrate** [comment]
this is done
