### ISSUE TITLE
Minor: snapp-example.ini generated with [example-snapp] commented out.

### ISSUE THREAD

**Issue by Sonofotis** [loki-project/loki-network#232]
When enabling persistent snapp's the `snapp-example.ini` file generates with [example-snapp] commented out. It would be nice once the line`#example-snapp=/home/modeify/.lokinet/snapp-example.ini` in `lokinet.ini` is uncommented the persistent SNApps works without having to configure `snapp-example.ini`

**Comment by majestrate** [comment]
right now there is a default snapp that can be persisted by adding `keyfile=/path/to/key.private` to the `[network]` section.

`[services]` section provides additional snapps and can get in the way, specifically when dns port is not properly specified.

**Comment by Sonofotis** [comment]
I see, I didn't know you could add `keyfile=/path/to/key.private` to `lokinet.ini` `[network]` section. I'll add that to the guide for persistent SNApps.
