### ISSUE TITLE
Config connections ignored

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#233]
So my ini has 
```
[connect]
neuro_lokinet-staging1=n-st-1.signed
```

and

```
[bootstrap]
add-node=n-st-1.signed
```

but it ignores and I get 
```
[1;31m[ERR] (305) Thu Jan 17 13:20:43 2019 PST llarp/router_contact.cpp:339	Failed to open ~/.lokinet/bootstrap.signed[0;0m
[1;33m[WRN] (305) Thu Jan 17 13:20:43 2019 PST llarp/router/router.cpp:1596	Bootstrap node yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy.snode is too old and needs to be refreshed[0;0m
```

and

`[1;31m[ERR] (305) Thu Jan 17 13:20:44 2019 PST llarp/router/router.cpp:781	we have no bootstrap nodes specified[0;0m`

**Comment by majestrate** [comment]
is `n-st-1.signed` in the current working directory?

**Comment by neuroscr** [comment]
Yes, I’m actually using an absolute path but stripped it because public

**Comment by majestrate** [comment]
this looks to have been merged into staging.

**Comment by neuroscr** [comment]
after putzing around with a bunch of related stuff and being confused by auto-made config files. I think we got this nailed down enough to consider it closed.
