### ISSUE TITLE
change lokinet's binary default to config-less ephemeral client

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#234]
Messenger is going to bundle their own copy of the lokinet distribution in their client. So since we're likely to have endusers be our largest use case and to make the project easier to bundle with other projects, we're going to make this the default.

**Comment by despair86** [comment]
would that imply needing to make `lokinet-bootstrap` part of the distribution?
(unless the loki-msgr client can handle that itself)

**Comment by neuroscr** [comment]
@despair86 good point, especially with expiring RCs, they need to be freshly downloaded (also every start until the nodedb is big enough) blocked by #80

**Comment by neuroscr** [comment]
No longer blocked but now related to #239

**Comment by neuroscr** [comment]
We still want to do this

**Comment by despair86** [comment]
this should have landed by v0.5.1 with the windows fixes
reopen if you need other things?
