### ISSUE TITLE
xxx.snode kills DNS

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#243]
Master branch bug

Small node case that reproduces the issue on MacOS

```js
const dns = require('dns');

function getRandomSnodeAddress(url) {
  /* resolve random snode */
  return new Promise((resolve, reject) => {
    dns.resolveCname(url, (err, address) => {
      if (err) {
        reject(err);
      } else {
        resolve(address[0]);
      }
    });
  });
}

function lookup(url) {
  /* resolve random snode */
  return new Promise((resolve, reject) => {
    dns.lookup(url, (err, address) => {
      if (err) {
        reject(err);
      } else {
        resolve(address);
      }
    });
  });
}

async function fetchME() {
  const node = await getRandomSnodeAddress('random.snode');
  const address = await lookup(node);
  console.log(address);
  console.log("loki net broke!")
}

fetchME();
```

**Comment by neuroscr** [comment]
dns.resolve4 works and doesn't break it

**Comment by majestrate** [comment]
does the dns server stop responding to requests?

**Comment by majestrate** [comment]
does the socket for dns still exist?

**Comment by BeaudanBrown** [comment]
After it breaks we can still access clearnet like normal, but if we try to ping a .snode address we get
`cannot resolve xxx.snode: Unknown host`
We can still do `nslookup xxx.snode 127.0.0.1` and it will give us the ip which we can then still ping

**Comment by majestrate** [comment]
what OS are you able to reproduce this on?

**Comment by BeaudanBrown** [comment]
Ah we did the node testing on Mikunj's mac, would have to ask him for the version soz. We think Sacha's mac also has been suffering from the same bug but we only started digging when it we noticed it happening to Mik as well so we haven't done the node test to confirm
I'll ask them to comment their OS versions when they can

**Comment by Mikunj** [comment]
Pretty sure mine is the latest (OSX Mojave 10.14.2) but i'll double check when i get back in the office on tuesday

**Comment by majestrate** [comment]
is ipv6 enabled?

**Comment by Mikunj** [comment]
> is ipv6 enabled?
No it's off
