### ISSUE TITLE
missing config, doesn't fail

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#251]
lokinet /path/to/a/file/that/doesnt/exist.ini

Doesn't fail out as expected

it actually just makes a new config file at the specified path even though no flags are passed

I'm thinking this should be a fatal error

**Comment by majestrate** [comment]
On Tue, Jan 29, 2019 at 09:53:49AM +0000, Ryan Tharp wrote:
> lokinet /path/to/a/file/that/doesnt/exist.ini
> 
> Does fail out as expected
> 
> it actually just makes a new config file at the specified path even though no flags are passed
> 
> I'm thinking this should be a fatal error

if ran with no paramters it should create the default config structure otherwise it should fail.

**Comment by neuroscr** [comment]
@majestrate agreed, if the default config location, auto-creation should be allowed without -g/-c options
