### ISSUE TITLE
suggestion: use #pragma once

### ISSUE THREAD

**Issue by cathugger** [loki-project/loki-network#27]
may be better optimized by compilers.
compiler support should be fine too.
also looks cleaner.

**Comment by cathugger** [comment]
though this could be moot because gcc already recognizes common ifndef guards: https://gcc.gnu.org/onlinedocs/cpp/Once-Only-Headers.html

**Comment by cathugger** [comment]
https://en.wikipedia.org/wiki/Pragma_once wikipedia page on that

**Comment by majestrate** [comment]
On Thu, Oct 11, 2018 at 10:03:05PM -0700, cathugger wrote:
> may be better optimized by compilers.
> compiler support should be fine too.
> also looks cleaner.

This would be a huge style shift, not sure it'd work.

If we do a restyle in the future I think we would probably use it.

**Comment by despair86** [comment]
still an unofficial compiler extension on UNIX
hit-or-miss

**Comment by cathugger** [comment]
gcc (except old version, but that probably doesn't support modern C++ features this project uses) and clang handle it. so does MSVC.
but yeah not supported officially in any C/C++ standard.
