### ISSUE TITLE
DNS replies on MacOS defer to alternate DNS

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#270]
MacOS is trying alt servers since our DNS server isn't recursive
`192.168.10.253` is my lokinet DNS, `8.8.8.8` is my alt

Wireshark is show 2 successful replies but that one bit is preventing it from being correct.

```
nslookup bs4556rgfuonapmqc95h8s7hyxi9bawdsnmkeffcpzsj15kt6nsy.snode
;; Got recursion not available from 192.168.10.253, trying next server
;; Got recursion not available from 192.168.10.253, trying next server
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find bs4556rgfuonapmqc95h8s7hyxi9bawdsnmkeffcpzsj15kt6nsy.snode: NXDOMAIN
```
MessageHeader::Decode just seems to read it in as a short, so fiddling the bits is a bit hard for the moment. But guessing we just need to always set that bit to true.

**Comment by majestrate** [comment]
actually i see the problem, it's not setting the right flags
