### ISSUE TITLE
IPv6 support inside tunnels

### ISSUE THREAD

**Issue by cathugger** [loki-project/loki-network#28]
Currently we only support IPv4 inside tunnels.
IPv4 should stay.
IPv6 to IPv6 communication could be added without too much trouble.
But IPv6 to IPv4 (and back) translation could be very tricky.
How we could approach this? How would DNS resolving relate to this?
Or we should not add IPv6 support at all?
IPv6 would work better for mapping large amount of peers.

**Comment by majestrate** [comment]
On Thu, Oct 11, 2018 at 10:37:56PM -0700, cathugger wrote:
> Currently we only support IPv4 inside tunnels.
> IPv4 should stay.
> IPv6 to IPv6 communication could be added without too much trouble.
> But IPv6 to IPv4 (and back) translation could be very tricky.
> How we could approach this? How would DNS resolving relate to this?
> Or we should not add IPv6 support at all?
> IPv6 would work better for mapping large amount of peers.

I was thinking of separting exit traffic to be ipv6 only and hidden services as ipv4 only.

I have 3 justifications for this descision:

1) there aren't any good deprecated or unused private ipv6 ranges left that I can use that I know of.

2) ipv4 only exits would be NAT'd HELL on earth.

3) would provide a clear separation between hidden service and exit traffic

**Comment by cathugger** [comment]
While I definitely want IPv6 support for exits, I'm unsure how to feel about IPv6-only. Some of things are still IPv4-only :\
You probably want to give globally routable IPv6 address (based on client' public key) to interface.
Should we support NPTv6 use case too? Unsure if having constant ULA NPTv6 address or changing-when-exit-changes globally routable IPv6 would be better..

>1) there aren't any good deprecated or unused private ipv6 ranges left that I can use that I know of.

could use some /48 or /64 subnet of fd00::/8 but yeah that's sorta ugly

>2) ipv4 only exits would be NAT'd HELL on earth.

end2end connectivity and possibility to host services would be sorta cool but unsure if it's critical use case

>3) would provide a clear separation between hidden service and exit traffic

imo could be separated by using packet destination address; we'd still use source address of zeros, and leave OS to handle NAT. less clear but not something impossibly confusing.

**Comment by majestrate** [comment]
On Fri, Oct 12, 2018 at 05:45:55AM -0700, cathugger wrote:
> While I definitely want IPv6 support for exits, I'm unsure how to feel about IPv6-only. Some of things are still IPv4-only :\
> You probably want to give globally routable IPv6 address (based on client' public key) to interface.
> Should we support NPTv6 use case too? Unsure if having constant ULA NPTv6 address or changing-when-exit-changes globally routable IPv6 would be better..
> 
> >1) there aren't any good deprecated or unused private ipv6 ranges left that I can use that I know of.
> 
> could use some /48 or /64 subnet of fd00::/8 but yeah that's sorta ugly

yup

> 
> >2) ipv4 only exits would be NAT'd HELL on earth.
> 
> end2end connectivity and possibility to host services would be sorta cool but unsure if it's critical use case

hence why ipv6 was chosen for exits, you can give each user their own /128

> 
> >3) would provide a clear separation between hidden service and exit traffic
> 
> imo could be separated by using packet destination address; we'd still use source address of zeros, and leave OS to handle NAT. less clear but not something impossibly confusing.

internally everything is represented as ipv6 anyways, including ipv4 addresses as hybrid dualstack addresses (::ffff:8.8.8.8)

that means we would probably use SIIT with NAT if we do any ipv4 exit traffic.

**Comment by cathugger** [comment]
>based on client' public key

nvm that's really bad idea for fingerprintability (and also exits would need to keep state of peers either way so not much would be gained with that).

**Comment by cathugger** [comment]
>that means we would probably use SIIT with NAT if we do any ipv4 exit traffic.

SIIT sounds like more work to do, and also has some edges like MTU being different for IPv4 and IPv6 (how the hell would his handled for tun interfaces? multiple of them?)

**Comment by majestrate** [comment]
On Fri, Oct 12, 2018 at 01:45:40PM +0000, cathugger wrote:
> >that means we would probably use SIIT with NAT if we do any ipv4 exit traffic.
> 
> SIIT sounds like more work to do, and also has some edges like MTU being different for IPv4 and IPv6 (how the hell would his handled for tun interfaces? multiple of them?)

for MTU we'll probably pick the smallest initially. it could be negotiated with the exit.

**Comment by cathugger** [comment]
>for MTU we'll probably pick the smallest initially.

I don't like that.

>it could be negotiated with the exit.

more work to do.

Is there anything really wrong with using same kind of IPv4 packets for exit traffic, other than "stuffing everything to IPv6 for that looks cleaner to me"?

**Comment by majestrate** [comment]
On Fri, Oct 12, 2018 at 01:54:30PM +0000, cathugger wrote:
> >for MTU we'll probably pick the smallest initially.
> 
> I don't like that.

same

> 
> >it could be negotiated with the exit.
> 
> more work to do.

yup

> 
> Is there anything really wrong with using same kind of IPv4 packets for exit traffic, other than "stuffing everything to IPv6 for that looks cleaner to me"?

we use ipv4 for the communication with the relays right now so i don't want to touch the ipv4 routes at the moment, will have to add routes for the first hop relays for clients anyways if we provide ipv4 exit traffic at all.

stuffing it over ipv6 makes more sense right now (at least to me) as all the addresess are represented as ipv6 internally.

**Comment by cathugger** [comment]
https://tools.ietf.org/html/rfc7915 (SIIT) seems like quite hell of work to do (and I don't want llarp to do this kind of work as it'll be possible bug source and even implemented properly still has some very undesirable properties like requiring lower MTU, handling of fragmentation), so I'd rather not have IPv4 support initially than have it implemented this way.

**Comment by cathugger** [comment]
Well, my current proposal for IPv4 exit traffic would be packets with client' src address set to `0.0.0.0` and dst address to globally routable (not in 0.0.0.0/8) IPv4 address.
Older clients have both src and dst addresses non-0.
Newer clients have both src and dst addresses 0.
Other IPv4 addresses from 0.0.0.0/8 range could be used for future extensions.

**Comment by cathugger** [comment]
>Older clients have both src and dst addresses non-0.
>Newer clients have both src and dst addresses 0.

clarification: for hidden service to hidden service traffic

for clearnet->client, src would be globaly routable IPv4 address, dst would be 0.0.0.0

**Comment by despair86** [comment]
no blockers on my end, i already require _some_ inet6 driver installed on the host system _just to read out RCs_

- `tcpip6.sys` in v5
- integrated into plain old `tcpip.sys` elsewhere

**Comment by majestrate** [comment]
i have implemented part of this in my ipv6-tun branch

**Comment by gh338** [comment]
> priv

it's possible that https://github.com/onioncat/onioncat/blob/master/glob_id.txt are not used at all.
At least i cannot connect to any of the ipv6 tor/i2p that are known.

**Comment by neuroscr** [comment]
closing since we have ipv6 code now
