### ISSUE TITLE
ICMP to tun IP from same machine fails

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#282]
Happens to me on MacOS
Beaudan also confirms also Ubuntu (also he can't do any communication with it (tcp?))
```
$ ping 10.200.0.1
PING 10.200.0.1 (10.200.0.1): 56 data bytes
Request timeout for icmp_seq 0
```

**Comment by majestrate** [comment]
fixed as of https://github.com/majestrate/loki-network/commit/e623e6fdb51ad4d52e127c26d203fd99878f1a30

**Comment by despair86** [comment]
when did that break? It was working in `master` (even on windows)
