### ISSUE TITLE
Auto detect CPU flags

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#297]
use cmake to determine needed flags

**Comment by despair86** [comment]
(I'd have suggested poring over the contents of `/proc/cpuinfo` but that falls apart outside of linux and cygwin

**Comment by VoidNV** [comment]
How about something like `-march=native`? or more reasonably, `-mtune=native`?

**Comment by despair86** [comment]
@VoidNV it already does, see `CMakeLists.txt`

**Comment by majestrate** [comment]
On Sat, Feb 09, 2019 at 09:06:57AM -0800, VoidNV wrote:
> How about something like `-march=native`? or more reasonably, `-mtune=native`?
I think this is related to detecting compile targets that have known bugs and applying a workaround,
all detected via cmake.

**Comment by majestrate** [comment]
i know that the debian packaging uses very generic flags by default.

**Comment by neuroscr** [comment]
https://cmake.org/cmake/help/latest/command/try_compile.html

**Comment by despair86** [comment]
should we close this? AMD and device manufacturers have released patches to microcode (and updated ROMs), and the standard GCC flags work fine now
