### ISSUE TITLE
filter address info bogon addresses

### ISSUE THREAD

**Issue by majestrate** [loki-project/loki-network#30]
we need to filter bogon addresses from being advertised
i.e.

* 0.0.0.0/8
* 127.0.0.1/8
* 10.0.0.0/8
* 192.168.0.0/16
* 21.0.0.0/8

probably more

**Comment by cathugger** [comment]
https://en.wikipedia.org/wiki/IPv4#Special-use_addresses

**Comment by majestrate** [comment]
On Sun, Oct 14, 2018 at 01:59:46PM -0700, cathugger wrote:
> https://en.wikipedia.org/wiki/IPv4#Special-use_addresses
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/loki-project/loki-network/issues/30#issuecomment-429662115

added in HEAD
