### ISSUE TITLE
Move miniupnp from lokid into lokinet

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#301]
Just letting everyone know I'm planning this. 

We'll use the JSONRPC to have lokid/messenger to request ports to be opened.

**Comment by majestrate** [comment]
explain

**Comment by neuroscr** [comment]
miniupnp lives in lokid but now lokid is going to include lokinet. Messenger is going to include lokinet but now also needs upnp. Instead of maintaining multiple copies, we should add this functionality of lokinet. It's the common networking base as the name suggests. It should handle all networking functions.

Alternatively it could be it's own daemon but I'd prefer to reuse the existing libabyss jsonrpc server instead of complicating packaging.

**Comment by majestrate** [comment]
yeah if it goes anywhere it's libabyss

**Comment by majestrate** [comment]
if there is any upnp in lokinet it would make the most sense to have lokinet be a port forwarding provider. trying to understand the use case here for a client.
