### ISSUE TITLE
NAT is broken

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#302]
Can't get lokinet router working on aws

we can confirm firewall is off, and tcp connections are fine. So there is no other AWS networking issue.

**Comment by BeaudanBrown** [comment]
Here's the config that my routers are using (incrementing ports, directory names and ifname by 1, plus ifaddr like `10.101.0.1/16` etc)
```
[router]
threads=4
contact-file=/home/ubuntu/net/lokinet0/self.signed
transport-privkey=/home/ubuntu/net/lokinet0/transport.private
ident-privkey=/home/ubuntu/net/lokinet0/identity.private
encryption-privkey=/home/ubuntu/net/lokinet0/encryption.private

public-address=3.104.58.138
public-port=1190

nickname=lokinet0


[api]
enabled=false
bind=127.0.0.1:1190


[system]
user=lokinet
group=lokinet
pidfile=/home/ubuntu/.lokinet/lokinet.pid


[dns]
upstream=1.1.1.1
bind=127.3.2.1:1100


[netdb]
dir=/home/ubuntu/net/lokinet0/netdb


[connect]
loki1=/home/ubuntu/net/lokinet1/self.signed


[lokid]
enabled=false
jsonrpc=127.0.0.1:22023


[network]
profiles=/home/ubuntu/net/lokinet0/profiles.dat
ifaddr=10.100.0.1/16
ifname=lokitun0
enabled=true
exit=false


[bind]
eth0=1090
```
Here are some pics of the EC2 instance configuration
![image](https://user-images.githubusercontent.com/43770694/52541343-f30e3280-2de7-11e9-9576-c7e784a0166d.png)
![image](https://user-images.githubusercontent.com/43770694/52541369-38cafb00-2de8-11e9-86df-241c8ddf1495.png)
![image](https://user-images.githubusercontent.com/43770694/52541382-54360600-2de8-11e9-89a9-a5a90bd87cdd.png)

**Comment by despair86** [comment]
ah

so this is why old GCP instance failed to relay packets sometime between v0.2.x and now

**Comment by majestrate** [comment]
i think it's the outbound udp port using a random high port that is causing this.

**Comment by majestrate** [comment]
you're advertising the wrong port with `public-port`
