### ISSUE TITLE
[bind] suggestion

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#327]
maybe it should be more like the following to be more inline with other options

use default port:
```
[bind]
enableRouter=eth0
```

use custom port 2099
```
[bind]
enableRouter=eth0:2099
```

If approaved, we can then push all dynamic keys to static ones. I think that would improve UX and lesson confusion.

**Comment by majestrate** [comment]
interfaces may have a `:` in their names in the case of vlans or something
