### ISSUE TITLE
localhost.loki and random.snode aren't working on windows

### ISSUE THREAD

**Issue by BeaudanBrown** [loki-project/loki-network#337]
Can nslookup localhost.loki but not random.snode
```
> nslookup random.snode 127.0.0.1
Server: localhost
Address: 127.0.0.1

Name: random.snode

> nslookup localhost.loki 127.0.0.1
Server: localhost
Address: 127.0.0.1

Name: localhost.loki
Address: 172.16.10.1
```
And when trying to use the messenger
`Error: queryCname ENOTFOUND localhost.loki at QueryReqWrap.onresolve`

Relevant JS:
```js
const dns = require('dns');
...
const resolve4 = url =>
  new Promise((resolve, reject) => {
    dns.resolve4(url, (err, ip) => {
      if (err) {
        reject(err);
      } else {
        resolve(ip);
      }
    });
  });
...
const resolveCname = url =>
  new Promise((resolve, reject) => {
    dns.resolveCname(url, (err, address) => {
      if (err) {
        reject(err);
      } else {
        resolve(address[0]);
      }
    });
  });
...
async getMyLokiIp() {
  const address = await resolveCname(this.localUrl); // localhost.loki
  return resolve4(address);
}
```

**Comment by majestrate** [comment]
localhost.loki doesn't have cname records it has A records

**Comment by majestrate** [comment]
wait no it does.

**Comment by majestrate** [comment]
are you using the system resolver or an explicitly defined dns server provided by lokinet?

**Comment by BeaudanBrown** [comment]
Ah system resolver I guess? You saying we should be doing something like this?
https://nodejs.org/api/dns.html#dns_dns_setservers_servers
Is there a way for us to determine at runtime which one we should use? (`127.0.0.1/127.3.2.1/whatever`?)
Or should we just assume that it is `127.0.0.1` except for linux?

**Comment by despair86** [comment]
@BeaudanBrown you *might* have forgotten to do that, I know next to nothing about node.js, but I would imagine it does not use the system resolver as part of its isolation/sandboxing model? hence the api described above

**Comment by despair86** [comment]
@BeaudanBrown what does `dns.getServers()` presently return?

**Comment by BeaudanBrown** [comment]
`dns.setServers()` gives `[10.0.2.3]` on my VM
After `dns.setServers(['127.0.0.1:53'])` I am able to resolve random.snode, but I can't seem to connect to any of the actual .snode addresses.
I think node-fetch is using its own instance of dns in the background so I tried to figure out how to do the equivalent of setServers for fetch and could only really find [this](https://www.npmjs.com/package/node-fetch#options)
(Relevant section `// http(s).Agent instance, allows custom proxy, certificate, dns lookup etc.`)
So I have been messing around with this 
```js
const fetchAgent = new http.Agent();

fetchAgent.createConnection = (args, cb) =>
  net.createConnection({
    port : args.port,
    host : args.host,
    lookup : (url) =>
      dns.resolve4(url, (err, ips) => {
        if (err) {
          return cb(err);
        }
        return cb(null, ips[0], 4);
      }),
  }, cb);

const fetchOptions = {
  method: options.type,
  body: JSON.stringify(body),
  headers: {
    'Content-Type': 'application/json',
  },
  timeout: options.timeout,
  agent: fetchAgent,
};
```
Which *seems* to be somewhat working (when I breakpoint in the callback of the `resolve4` call attached to `lookup` it is being called and is resolving a .snode address to an ip), but then the requests all just timeout)

**Comment by BeaudanBrown** [comment]
My VM with this code reports
`network timeout at xxx.snode:8079/retrieve`
While Jimmy's windows machine has lokinet crash and reports
```
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
```

**Comment by majestrate** [comment]
make a new issue with backtrace please.
this is resolved now?

**Comment by BeaudanBrown** [comment]
Yes random.snode and localhost.loki are working now after manually pointing to lokinet dns
Will try get some logs and make a new issue for the .snode crashes
