### ISSUE TITLE
linux: tcp_conn error: Success

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#352]
Guessing "Success" shouldn't be an error, leaves the 2nd line of failure to be questionable.

```
[ERR] (162) Tue Feb 26 02:12:06 2019 UTC /root/loki-daemon-launcher/src/loki-network/llarp/ev/ev_epoll.cpp:583	tcp_conn error: Success
[ERR] (162) Tue Feb 26 02:12:06 2019 UTC libabyss/src/client.cpp:379	failed to connect to RPC, dropped all pending calls
```

also this spamming the screen, can we reduce the frequency to only once per second?

**Comment by majestrate** [comment]
On Tue, Feb 26, 2019 at 02:13:47AM +0000, Ryan Tharp wrote:
> Guessing "Success" shouldn't be an error, leaves the 2nd line of failure to be questionable.
> 
> ```
> [ERR] (162) Tue Feb 26 02:12:06 2019 UTC /root/loki-daemon-launcher/src/loki-network/llarp/ev/ev_epoll.cpp:583	tcp_conn error: Success
> [ERR] (162) Tue Feb 26 02:12:06 2019 UTC libabyss/src/client.cpp:379	failed to connect to RPC, dropped all pending calls
> ```
> 
> also this spamming the screen, can we reduce the frequency to only once per second?
i never actually tested this codepath lol

**Comment by despair86** [comment]
>`strerror(0);`
heh

**Comment by neuroscr** [comment]
I think this is resolved, I haven't seen it in a bit
