### ISSUE TITLE
jsonrpc linux hanging

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#355]
curl http://127.0.0.1:28082 is just hanging on linux...

tcp        6      0 127.0.0.1:28082         0.0.0.0:*               LISTEN      20096/src/loki-netw 
tcp       61      0 127.0.0.1:28082         127.0.0.1:55526         CLOSE_WAIT  -                   
tcp       61      0 127.0.0.1:28082         127.0.0.1:36750         CLOSE_WAIT  -                   
tcp       60      0 127.0.0.1:28082         127.0.0.1:35014         ESTABLISHED -                   
tcp       61      0 127.0.0.1:28082         127.0.0.1:43512         CLOSE_WAIT  -                   
tcp       61      0 127.0.0.1:28082         127.0.0.1:54590         CLOSE_WAIT  -                   
tcp       61      0 127.0.0.1:28082         127.0.0.1:46386         CLOSE_WAIT  -

**Comment by majestrate** [comment]
is that the jsonrpc port or the binary port on lokid?

**Comment by neuroscr** [comment]
jsonrpc port on lokinet, see the stacktrace I posted

**Comment by neuroscr** [comment]
might be related to #357 if that one really isn't kqueue related

**Comment by neuroscr** [comment]
I can open the port now
