### ISSUE TITLE
Invalid snode addresses in `Target key` logs

### ISSUE THREAD

**Issue by BeaudanBrown** [loki-project/loki-network#363]
All of my messenger net nodes are reporting
`[WRN] lokinet0 (235) Thu Feb 28 05:07:34 2019 UTC dht/messages/gotrouter.cpp:156	Target key knonoyecm6arhz8b8rhun9awmjm3ds55ns5s8kky7t55m77hkzpy.snode`
with many different .snode addresses

I have found two instances so far where the address logged actually matches one of my relays, while the vast majority are just random addresses that don't exist
The two logs of relays that did exist were only logged once, while the invalid addresses are repeated many times in quick succession

Here's a few examples of the randoms in case there is something to gleam from them
```
p4fay6oqca8ufbpc6i6uurex977apzi4qu6f5dej5wehuwjussby.snode
htd7jpnnp1m35jgwsb68qgyxjy19z7q1e6esonkx3dju3dttygcy.snode
7sap6qz8xbsc7imhjf81kbwnqpijpj5rm41dpg9rq5qnandabt9y.snode
a1scqt7fnkkysz5o7yjbaht6zo53hexg48ys39jz8q54mjyepx1y.snode
```

Also potentially of interest is this log
`[WRN] lokinet4 (603) Thu Feb 28 03:45:33 2019 UTC dht/messages/gotintro.cpp:156    Target key yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy.loki`
which shows up a few times

Also present are .loki addresses that aren't just yyy
`[WRN] lokinet0 (235) Thu Feb 28 04:51:21 2019 UTC dht/messages/gotintro.cpp:156	Target key nxsrdx6m6faot9mydopnx3no8y1y9ucnk33g8ebqwnrpj6whdjzo.loki`

Potentially memory bug??

**Comment by michael-loki** [comment]
@BeaudanBrown seen this recently? else this should probably be closed
