### ISSUE TITLE
DNS issues on OSX

### ISSUE THREAD

**Issue by sachaaaaa** [loki-project/loki-network#372]
I'm having this issue while attempting to run the messenger over lokinet.
Not sure if this is related to any existing issue.

Basically using staging branch on OSX, The following works
* `nslookup random 127.0.0.1`
* `nslookup <address.snode> 127.0.0.1`
* `ping <snode ip>`
* `http://<snode ip>:<port>/json_rpc` 

But this doesn't work:
* `http://<address.snode>:port/json_rpc` ==> timeout
And this above is what the messenger tries to query.

**Comment by michael-loki** [comment]
99% sure @majestrate fixed this.
