### ISSUE TITLE
Failed DNS resolution 

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-network#394]
This occurred on Linux 18.04 with on commit 4e9276e232b356b47c702abec9c577e4d2e132e7 for the staging branch. This occurred on Beau's Sydney Messenger net in which all nodes are also running 4e9276e232b356b47c702abec9c577e4d2e132e7 

Behaviour, Run lokinet for 1 hour along with Loki messenger, add multiple user public keys so multiple "Swarms" must be contacted through lokinet regularly. 

After about an hour i am unable to send a message to particular pub keys, this is because i am failing to resolve to a particular SNODE.

Using NSLOOKUP i get 

```
nslookup e3eai9uukrm1khk8w9exji1pu5bo4jmzz4gwyzyoyx6hqssge3jo.snode
;; Warning: Message parser reports malformed message packet.
Server:		127.3.2.1
Address:	127.3.2.1#53

** server can't find e3eai9uukrm1khk8w9exji1pu5bo4jmzz4gwyzyoyx6hqssge3jo.snode: NXRRSET
```

Beau tested this on his Lokinet and he can resolve to the SNODE perfectly, all 4 other nodes in the Messenger net are resolving for my lokinet client fine, its just this one node.

**Comment by majestrate** [comment]
The new behavior is to defer dns responses until packets are sendable to the resolved endpoint. It sounds like it may be that path builds are now too slow for this behavior. possibly.

**Comment by KeeJef** [comment]
What would cause the path builds to be slow? they seem quite fast considering that messenger net is a single node run in Sydney (low latency to melb office) that has 5 lokinet routers.

**Comment by majestrate** [comment]
that is just a possible reason, it may be something else if that is the case.

**Comment by KeeJef** [comment]
i think possibly the best way to test for this is to just try and resolve to random.snode on a loop until  resolution fails. its hard for us to tell why its failing though

**Comment by majestrate** [comment]
right, the why part can't be sent via dns afaik

**Comment by majestrate** [comment]
does that one node actually exist on the test network?

**Comment by KeeJef** [comment]
Yup, its one of the 5 i believe

**Comment by KeeJef** [comment]
Actually it might not belong.... @BeaudanBrown sent me this message last Tuesday with some nodes, but im not sure if these are the Sydney net nodes 

`"http://fxyauypeo7pyfufti7biobhy15n13eamkicit5r174cokwtoibay.snode/", "http://zm3qhfu788d5g1ok16rc1niow14orjbkhx1d67my5ouc64r5outy.snode/" ], [ "http://mguz18b154muzxetjjpoyyxbcjjhodm8eh1zctzhuo58rzmcoipy.snode/", "http://cuxahcq1roz4hmh6z7y9bs46s1859n1oknfxqkk9h14b3t34qa8y.snode/" ], [ "http://cuzu9my79ebbnasptrr13qsksg8dn49ddbbefbw9qb6jg9trx49y.snode/", "http://7qgnwx5pz6duogbsjjdw7drrym6xwyecsc88pjy7a6siejsr7k4y.snode/"`

can you confirm the nodes in the Sydney testnet @BeaudanBrown ? if this is the case it seems that node doesnt exist but i also remember beau testing his connection to the node so this

**Comment by BeaudanBrown** [comment]
These are all the singapore nodes

**Comment by majestrate** [comment]
are these nodes on the same test network?

**Comment by KeeJef** [comment]
No those are the Singapore nodes, the Sydney testnet has a different set nodes, Beau gave you the bootstrap right ?

**Comment by majestrate** [comment]
that's the problem then, these are 2 seperate test networks.

**Comment by BeaudanBrown** [comment]
@majestrate I am still getting this issue as of today, I am definitely on the right network and the nodes are definitely running and seem to be logging nothing out of the ordinary
```
beaudan@beaudan-pc:~/workspace/loki-messenger$ nslookup we1qu4uq6oji1ciochaknfazaj1yn1x6dposnopn6wuju3d5gb7o.snode
;; Warning: Message parser reports malformed message packet.
Server:		127.3.2.1
Address:	127.3.2.1#53

** server can't find we1qu4uq6oji1ciochaknfazaj1yn1x6dposnopn6wuju3d5gb7o.snode: NXRRSET
```
Getting this for 2 / 10 nodes
Nuking my netdb and restarting client fixes the issue so I guess it is something client side

**Comment by KeeJef** [comment]
are you still getting this @BeaudanBrown ? don't think I've been experiencing this on the latest builds

**Comment by KeeJef** [comment]
haven't seen this in a while myself, going to assume because @BeaudanBrown didn't respond he's not getting this either
