### ISSUE TITLE
DNS stops working after period of time.

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#401]
```
Doyle: Hmm, lokinet setup stopped my DNS from resolving normal websites, had to disable it in resolvconf and reload my network manager to get it working again. This happened over the weekend, PC has been restarted a couple of times
[4:33 PM] Doyle: lubuntu 18.10
```

Confirms my findings on 3/14

**Comment by neuroscr** [comment]
Jeff if that was the case, it'd be 394. And if DNS is always working for you, just let us test and we'll close this out.

**Comment by majestrate** [comment]
dns never stopped working outright on any of my dev branches, i haven't even touched that code.

**Comment by neuroscr** [comment]
Note, my 3/14 may have been caused by the exit tun dns issue and unrelated to this issue.

**Comment by despair86** [comment]
highly doubt it
otherwise i wouldn't be able to reconnect to IRC after an outage

**Comment by KeeJef** [comment]
Haven't had this for weeks, its timeouts instead of DNS issues now
