### ISSUE TITLE
DHT explore not working

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#424]
lokid staked, routers permitted.

Clear the nodedb and now it's staying empty.

**Comment by BeaudanBrown** [comment]
Potentially related: if I ever restart my nodes, they all repeat something along these lines
```
[WRN] lokinet0 (894) Mon Mar 25 00:00:09 2019 UTC handlers/exit.cpp:202	default-connectivity dropping packet, has no session at 155.57.109.249
[NFO] lokinet0 (894) Mon Mar 25 00:00:19 2019 UTC dht/context.cpp:296	Exploring network via 1 peers
[WRN] lokinet0 (894) Mon Mar 25 00:00:19 2019 UTC dht/context.cpp:98	Not enough dht nodes, have 0 want 1
[ERR] lokinet0 (894) Mon Mar 25 00:00:19 2019 UTC dht/context.cpp:305	failed to select random nodes for exploration
```
Nuking the netdb and restarting all the nodes fixes the issue, and if I only restart a few of my nodes at a time they seem to recover by themselves.
But if I stop the whole network they won't communicate unless I also nuke the netdb

**Comment by majestrate** [comment]
7065b00c221f0748fc1f8fbd3bcff69268357c4d should have fixes for this

**Comment by neuroscr** [comment]
fixed today

**Comment by neuroscr** [comment]
had to do with the service list not retrying out going connections
