### ISSUE TITLE
MetricTank metric publisher privacy issues

### ISSUE THREAD

**Issue by michael-loki** [loki-project/loki-network#449]
We want to have an **explicitly** opt in metric publisher which would help lokinet developers collect performance metrics on testnets only by posting to a metrictank or similar instance running somewhere.

Making this a public issue to brainstorm ideas on how we make sure this is very very opt in, and we don't accidentally leak privacy.

My ideas:
1. command line parameter
2. environment variable
3. log in massive letters at start up
4. require a "yes" at `stdin` to enable

I think that a combination of 1, 2 and 3 is sufficient. 4 would probably make automation more painful than we want it to be.

**Comment by KeeJef** [comment]
I'm assuming startup flags would work fine, its what is usually used across the Lokinet apps (Lokid, launcher, lokinet), so 
`./lokinet --expose-metrics `
or something similar

**Comment by michael-loki** [comment]
We went with option in config file + environment variable + big warning.
