### ISSUE TITLE
More formal logging support

### ISSUE THREAD

**Issue by michael-loki** [loki-project/loki-network#450]
eg support for syslog, logging to file, splunk, etc

**Comment by neuroscr** [comment]
we're going to put syslog support into the launcher, so the other daemons in the suite can benefit from it.

**Comment by majestrate** [comment]
adding this rn

**Comment by majestrate** [comment]
refactored logging and added syslog and stdout logging, just need file logging.

**Comment by majestrate** [comment]
file logging / syslog / refactored logging has been merged, what else do we want for this?
