### ISSUE TITLE
Bad request success rate

### ISSUE THREAD

**Issue by BeaudanBrown** [loki-project/loki-network#451]
A lot of nodes have been getting path timed out for several minutes and cannot be resolved, this seems to resolve itself after some time tho
On latest staging, some nodes get stuck in `failed to select hop 3` loop and then can never be resolved with nslookup
These nodes are not present in my client netdb
Restarting my client sometimes allows these nodes to be found but I still have not been able to get a full netdb

**Comment by BeaudanBrown** [comment]
Getting a combination of `NXRRSET` with `Message parser reports malformed message packet.`
And `connection timed out; no servers could be reached`

**Comment by majestrate** [comment]
On Tue, Mar 26, 2019 at 04:31:47PM -0700, Beaudan Campbell-Brown wrote:
> A lot of nodes have been getting path timed out for several minutes and cannot be resolved, this seems to resolve itself after some time tho
> On latest staging, some nodes get stuck in `failed to select hop 3` loop and then can never be resolved with nslookup
> These nodes are not present in my client netdb
That's what is causing it, I have a PR coming in that changes the behavior of the dht slightly so that the network doesn't segment.
