### ISSUE TITLE
cant compile in cygwin

### ISSUE THREAD

**Issue by lostfile** [loki-project/loki-network#476]
$ cmake ..
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++.exe
-- Check for working CXX compiler: /usr/bin/c++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using the single-header code from /home/lostfile/loki-network/vendor/nlohmann/single_include/
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
CMake Error at CMakeLists.txt:318 (message):
  Your operating system is not supported yet

-- Configuring incomplete, errors occurred!
See also "/home/lostfile/loki-network/build/CMakeFiles/CMakeOutput.log".

**Comment by majestrate** [comment]
compiler versions please

**Comment by despair86** [comment]
cygwin is not supported except with `-mno-cygwin` (to emit a native app)

**Comment by despair86** [comment]
even then, you're going to want to get a native compiler suite (think red hat carries a version of mingw-w64 in cygwin pkgs)

**Comment by lostfile** [comment]
my gcc (GCC) 7.4.0
g++ (GCC) 7.4.0
cmake version 3.13.1

**Comment by despair86** [comment]
- cygwin's implementation of BSD sockets directly conflicts with winsock2, which causes nightmares for native windows apps
- the Windows NT port of this software is fully native, and requires only Microsoft libc v6.1 or later (ergo, Windows 2000/XP)
