### ISSUE TITLE
config order issue: router.identity-privkey or router.ident-privkey can stomp lokid.service-node-seed

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#481]
looks like lokid.service-node-seed is enough to load the service address as the identity, HOWEVER, it has to be after any router.identity-privkey or router.ident-privkey

**Comment by majestrate** [comment]
are you sure?
https://github.com/loki-project/loki-network/blob/master/llarp/router/router.cpp#L961

**Comment by neuroscr** [comment]
that line has to do with nickname with has no relation to what I'm talking about

**Comment by majestrate** [comment]
the code changed a bit, it's right here https://github.com/loki-project/loki-network/blob/fdc4b9c4bd87e6165bd8dd0d87dbef17a1fcbd70/llarp/router/router.cpp#L976

linking via commit now :P
