### ISSUE TITLE
Supernode deregistered with no real warning on windows console

### ISSUE THREAD

**Issue by MetallianFR68** [loki-project/loki-network#484]
I have to share my bad experience with the windows build.
I was running a supernode for 3 days.
After day 3, it was suddenly unregistered.
The attached log file seems very strange to me.
During 24 hours, the console continued to send "proof of life" quite often.
It's only when I restarted the process because I didn't get any more block reward that an error message appeared saying that the node was unregistered.

This was very confusing.
Now my stake is locked for 30 days and I'm very sorry about that.

I was running on a top notch machine, with high bandwidth connection (200Mb/200mb), backup connection and backup battery.

I think that the console log should be more explicit.
I also think that the penalty of the stake beeing locked for 30 days is way to much.

[lokid.txt](https://github.com/loki-project/loki-network/files/3041238/lokid.txt)

**Comment by neuroscr** [comment]
wrong repo, you want https://github.com/loki-project/loki
