### ISSUE TITLE
missing profiles.dat after latest build

### ISSUE THREAD

**Issue by necro-nemesis** [loki-project/loki-network#488]
[WRN] (132) Fri Apr  5 06:38:25 2019 EDT profiling.cpp:212      failed to load router profiles from /home/user/.lokinet/profiles.dat

daemon halts.

profiles.dat does not exist in the user .lokinet directory. Does not exist in the /root/.lokinet directory also.

**Comment by majestrate** [comment]
what does your config look like?

**Comment by necro-nemesis** [comment]
[router]
# number of crypto worker threads 
threads=4
# path to store signed RC
contact-file=/root/.lokinet/self.signed
# path to store transport private key
transport-privkey=/root/.lokinet/transport.private
# path to store identity signing key
ident-privkey=/root/.lokinet/identity.private
# encryption key for onion routing
encryption-privkey=/root/.lokinet/encryption.private

# uncomment following line to set router nickname to 'lokinet'
# nickname=lokinet


# admin api (disabled by default)
[api]
enabled=false
# authkey=insertpubkey1here
# authkey=insertpubkey2here
# authkey=insertpubkey3here
bind=127.0.0.1:1190


# system settings for privileges and such
[system]
user=lokinet
group=lokinet
pidfile=/root/.lokinet/lokinet.pid


# dns provider configuration section
[dns]
# resolver
upstream=1.1.1.1
bind=127.3.2.1:53


# network database settings block 
[netdb]
# directory for network database skiplist storage
dir=/root/.lokinet/netdb


# bootstrap settings
[bootstrap]
# add a bootstrap node's signed identity to the list of nodes we want to bootstrap from
# if we don't have any peers we connect to this router
add-node=/root/.lokinet/bootstrap.signed
# add another bootstrap node
#add-node=/path/to/alternative/self.signed




# snapps configuration section
[services]# uncomment next line to enable persistant snapp
#example-snapp=/root/.lokinet/snapp-example.ini


# network settings 
[network]
profiles=/root/.lokinet/profiles.dat
# uncomment next line to add router with pubkey to list of routers we connect directly to
#strict-connect=pubkey
# uncomment next line to use router with pubkey as an exit node
#exit-node=pubkey
ifname=lokitun0
ifaddr=172.16.10.1/24
enabled=true

**Comment by necro-nemesis** [comment]
but without the shouting.

**Comment by necro-nemesis** [comment]
I removed the comment hash to make it more eye friendly but they are there in the file.

**Comment by majestrate** [comment]
On Fri, Apr 05, 2019 at 05:07:03AM -0700, necro-nemesis wrote:
> [router]
> # number of crypto worker threads 
> threads=4
> # path to store signed RC
> contact-file=/root/.lokinet/self.signed
> # path to store transport private key
> transport-privkey=/root/.lokinet/transport.private
> # path to store identity signing key
> ident-privkey=/root/.lokinet/identity.private
> # encryption key for onion routing
> encryption-privkey=/root/.lokinet/encryption.private
> 
> # uncomment following line to set router nickname to 'lokinet'
> # nickname=lokinet
> 
> 
> # admin api (disabled by default)
> [api]
> enabled=false
> # authkey=insertpubkey1here
> # authkey=insertpubkey2here
> # authkey=insertpubkey3here
> bind=127.0.0.1:1190
> 
> 
> # system settings for privileges and such
> [system]
> user=lokinet
> group=lokinet
> pidfile=/root/.lokinet/lokinet.pid
> 
> 
> # dns provider configuration section
> [dns]
> # resolver
> upstream=1.1.1.1
> bind=127.3.2.1:53
> 
> 
> # network database settings block 
> [netdb]
> # directory for network database skiplist storage
> dir=/root/.lokinet/netdb
> 
> 
> # bootstrap settings
> [bootstrap]
> # add a bootstrap node's signed identity to the list of nodes we want to bootstrap from
> # if we don't have any peers we connect to this router
> add-node=/root/.lokinet/bootstrap.signed
> # add another bootstrap node
> #add-node=/path/to/alternative/self.signed
> 
> 
> 
> 
> # snapps configuration section
> [services]# uncomment next line to enable persistant snapp
> #example-snapp=/root/.lokinet/snapp-example.ini
> 
> 
> # network settings 
> [network]
> profiles=/root/.lokinet/profiles.dat

looks like profiles.dat is to be located at /root/.lokinet/profiles.dat

what is the full output that is yielded?

**Comment by necro-nemesis** [comment]
[NFO] (180) Fri Apr  5 08:18:41 2019 EDT daemon/main.cpp:243    Running from: /root/.lokinet
[NFO] (180) Fri Apr  5 08:18:41 2019 EDT daemon/main.cpp:244    Using config file: /root/.lokinet/lokinet.ini
[NFO] (180) Fri Apr  5 08:18:41 2019 EDT context.cpp:146        lokinet-0.4.0-ebf12a50 (dev build)
[NFO] (180) Fri Apr  5 08:18:41 2019 EDT context.cpp:147        starting up
[NFO] (180) Fri Apr  5 08:18:41 2019 EDT router/router.cpp:869  set local dns to 127.3.2.1:53
[NFO] (180) Fri Apr  5 08:18:41 2019 EDT router/router.cpp:864  add upstream resolver 1.1.1.1
[NFO] (180) Fri Apr  5 08:18:41 2019 EDT router/router.cpp:864  add upstream resolver 1.1.1.1
[NFO] (180) Fri Apr  5 08:18:41 2019 EDT router/router.cpp:864  add upstream resolver 1.1.1.1
[ERR] (180) Fri Apr  5 08:18:41 2019 EDT router_contact.cpp:286 netid missmatch: '[ "staging" ]' != '[ "testnet" ]'
[ERR] (180) Fri Apr  5 08:18:41 2019 EDT router/router.cpp:899  malformed rc file='/root/.lokinet/bootstrap.signed' rc=[ k = [ "494e49daddfd9f13e13453e452665078b18634f4bc5dc2aafb330c78418a9020" ] updated = 1554154305452 netid = [ "staging" ] v = 0 ai = [ [ ip = "::ffff:206.81.100.174" port = 2091 ] ] xi = [ ] e = [ "abcda4678d3210e7a589ca6c47423befb1de934751314c78ea92a4d6c7484b44" ] z = [ "46d04cb88d2f0257b25553c35f884bc5baf7848a6d7be1c7cd139412d0811c04ede0ef0ac3fd575688ee2d12e45f1c3602a400c4a404b3998a8480cdea302e04" ] ]
[WRN] (180) Fri Apr  5 08:18:41 2019 EDT profiling.cpp:212      failed to load router profiles from /root/.lokinet/profiles.dat
[NFO] (180) Fri Apr  5 08:18:41 2019 EDT router/router.cpp:777  setting profiles to /root/.lokinet/profiles.dat
[NFO] (180) Fri Apr  5 08:18:41 2019 EDT context.cpp:111        nodedb_dir loaded 0 RCs from [/root/.lokinet/netdb]
[WRN] (180) Fri Apr  5 08:18:41 2019 EDT profiling.cpp:212      failed to load router profiles from /root/.lokinet/profiles.dat
[NFO] (180) Fri Apr  5 08:18:41 2019 EDT router/router.cpp:1411 You have 0 inbound links
[NFO] (180) Fri Apr  5 08:18:41 2019 EDT router/router.cpp:1444 Signing rc...
[ERR] (180) Fri Apr  5 08:18:41 2019 EDT router_contact.cpp:309 invalid signature
buffer of size 1024
d1:ale1:i7:testnet1:k32:.......s..31ZRY...6.Z.H....m$...1:p32:...y...&....-h.....G..`E% ..@..F1:ui1554466721758e1:vi0e1:xle1:z64
:I....W..-.V.BJ..7.......7.5.a~r..{.%D.n......F.:.N..u..x.U.-....e......................p...............#...m...........^.......
`.,.m....................@..m...@Na.m...+.Z.m...............[U./P.......`.................o.i.....................o.i.....T.m...
@Na.m.....8.@V.........tH.d.@V....d.@V..5.......P.........d.@V......@V......................[U./....@V..^.......^........G;.@V..
 .`.m.............`.m.....a.m.......@V......@V......@V......@V......@V......@V...fa.m...............@V..................ERR] (1.
@.`.m...............................@V..........................................................................................
........................................................................ ........fa.m........... .......x........`a.m...0`a.m...
@`a.m.......[U./.........B..@V..p.......[.;.@V..0.........o.i.......@V...B..@V..P........................C..@V..p.......hC..@V..

[ERR] (180) Fri Apr  5 08:18:41 2019 EDT router/router.cpp:488  RC is invalid, not saving
[ERR] (180) Fri Apr  5 08:18:41 2019 EDT router/router.cpp:1453 failed to save RC

**Comment by necro-nemesis** [comment]
Should I be building "testnet" atm?

**Comment by majestrate** [comment]
On Fri, Apr 05, 2019 at 05:19:20AM -0700, necro-nemesis wrote:
> [NFO] (180) Fri Apr  5 08:18:41 2019 EDT daemon/main.cpp:243    Running from: /root/.lokinet
> [NFO] (180) Fri Apr  5 08:18:41 2019 EDT daemon/main.cpp:244    Using config file: /root/.lokinet/lokinet.ini
> [NFO] (180) Fri Apr  5 08:18:41 2019 EDT context.cpp:146        lokinet-0.4.0-ebf12a50 (dev build)
> [NFO] (180) Fri Apr  5 08:18:41 2019 EDT context.cpp:147        starting up
> [NFO] (180) Fri Apr  5 08:18:41 2019 EDT router/router.cpp:869  set local dns to 127.3.2.1:53
> [NFO] (180) Fri Apr  5 08:18:41 2019 EDT router/router.cpp:864  add upstream resolver 1.1.1.1
> [NFO] (180) Fri Apr  5 08:18:41 2019 EDT router/router.cpp:864  add upstream resolver 1.1.1.1
> [NFO] (180) Fri Apr  5 08:18:41 2019 EDT router/router.cpp:864  add upstream resolver 1.1.1.1
> [ERR] (180) Fri Apr  5 08:18:41 2019 EDT router_contact.cpp:286 netid missmatch: '[ "staging" ]' != '[ "testnet" ]'

you're on the wrong network, either set netid=staging in router section or use the main network

**Comment by necro-nemesis** [comment]
[router] section of lokinet.ini? Not defined there presently. "netid=staging" there didn't solve it. Misunderstand the entry or the pitfall that took me to the wrong network in the first place.

**Comment by majestrate** [comment]
On Fri, Apr 05, 2019 at 07:47:39AM -0700, necro-nemesis wrote:
> [router] section of lokinet.ini? Not defined there presently. "netid=staging" there didn't solve it. Misunderstand the entry or the pitfall that took me to the wrong network in the first place.
your bootstrap node is on the wrong network. staging network isn't up as far as i know.

**Comment by necro-nemesis** [comment]
https://cdn.discordapp.com/attachments/524098790899187712/562054803849740299/bootstrap.signed
http://206.81.100.174/n-st-1.signed
http://206.81.100.174/n-st-5.signed

These are the three bootstraps I have tried. Not sure which is valid atm.

**Comment by majestrate** [comment]
On Fri, Apr 05, 2019 at 08:19:24AM -0700, necro-nemesis wrote:
> https://cdn.discordapp.com/attachments/524098790899187712/562054803849740299/bootstrap.signed
> http://206.81.100.174/n-st-1.signed
> http://206.81.100.174/n-st-5.signed
> 
> These are the three bootstraps I have tried. Not sure which is valid atm.

these are on the internal staging network unless you know how to use these please use the default bootstrap points.
