### ISSUE TITLE
Store log file

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-network#522]
Currently it seems lokinet logs are just written to stdout, it would be good if we could store the most recent Lokinet sessions log in the .lokinet folder, this would allow users to easily grab the log files and attach them to issues if needed.

**Comment by majestrate** [comment]
done in https://github.com/majestrate/loki-network/commit/9503cc66f0ca1576f534b6c85d92420c7b1da234

will merge soon

**Comment by majestrate** [comment]
this has been merged
