### ISSUE TITLE
Resolve *.lokiaddress.loki

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-network#563]
Quote from Jagerman  

> Some tools (looking at Firefox) have an idiotic default of adding "www." when a name resolution fails, and then keeping it in the address bar even if name resolution fails with the "www.".  It might also be useful, however, for SNApps that want to set up name-based vhosts, but Perhaps it would be beneficial to make *.lokiaddress.loki resolve.

**Comment by majestrate** [comment]
adding this now

**Comment by majestrate** [comment]
https://github.com/loki-project/loki-network/pull/564

**Comment by majestrate** [comment]
this has been merged
