### ISSUE TITLE
Windows (after installing lokinet and launching) .loki leaked to ISP dns 

### ISSUE THREAD

**Issue by Patrickdurbin** [loki-project/loki-network#573]
**Describe the bug**
After I installed lokinet I launched it on windows version 1809. 
![image](https://user-images.githubusercontent.com/36722911/56962782-fda1b380-6b1c-11e9-8841-6c3af250d8f5.png)
![image](https://user-images.githubusercontent.com/36722911/56962843-17db9180-6b1d-11e9-94d3-ec64fa943b67.png)

I then opened up my browser and pasted a .loki address in at which point 
it went to this. 
![image](https://user-images.githubusercontent.com/36722911/56962943-540ef200-6b1d-11e9-8def-6985d28a5f67.png)

![image](https://user-images.githubusercontent.com/36722911/56963035-96383380-6b1d-11e9-9020-8210488b8707.png)
it reconnects and disconnects fine within the terminal I see action happening. 
Am I doing something wrong are missing a step? 

Torrents work just fine. Its as if my browser doesn't know lokinet is there and doesn't know how to use the address. Literaly Tor sites do the exact same thing if im not on the Tornet.

**Comment by majestrate** [comment]
torrents are being anonymized because no exits are configured.

**Comment by Patrickdurbin** [comment]
Im talking about the fact my browser doesn't know what to do with the .loki address it acts 100 percent the same for any type of address it doesn't understand it sends it directly to the ISP dnserrorassist.  Sorry if I wasn't clear.

**Comment by majestrate** [comment]
did you do an explicit `http://` prefix? if it doesn't have that the browser will depending on which one go with a search engine because of the non standard gtld in use.

**Comment by Patrickdurbin** [comment]
**without**

![image](https://user-images.githubusercontent.com/36722911/57006055-1a80ca00-6ba3-11e9-8bd6-5d7896e1466c.png)

**with**

![image](https://user-images.githubusercontent.com/36722911/57006072-4308c400-6ba3-11e9-8a2c-0818c9739df7.png)

**Comment by majestrate** [comment]
you're missing an i at the beginning of that address

**Comment by majestrate** [comment]
http://icxqqcpd3sfkjbqifn53h7rmusqa1fyxwqyfrrcgkd37xcikwa7y.loki/

**Comment by majestrate** [comment]
good find regardless.
