### ISSUE TITLE
Implement cname delay hack (was DNS resolution leakages)

### ISSUE THREAD

**Issue by jagerman** [loki-project/loki-network#574]
A resolution for a whatever.loki address can currently leak to upstream nameservers if resolution takes too long: the request to lokinet's resolver times out and the OS tries the next configured DNS server, which leaks the loki address to the DNS server. (One tester on a nasty, major US ISP then got a ISP-branded internet search page for the .loki address).

This was a consequence of #486 (which avoided the need for manual DNS server configuration or an automatic global fallback and breaks local resolution).

I'm not sure what the solution is; some of the options are:

- Replace all resolvers with lokinet with default geo-balanced DNS (8.8.8.8 or the like), and have lokinet perform all DNS lookups (forwarding non-lokinet addresses to the remote).
    - Upside: lokinet address lookups can't leak.
    - Downside: all DNS resolution stops working if lokinet is stopped
    - Downside: breaks common local DNS resolution for things like local network routers
    - Downside: adds latency to all DNS lookups (because lokinet isn't a caching nameserver, unlike most local routers)
- Put lokinet first, but not exclusive, in the resolver list, and SERVFAIL for non-local requests (this is what happens since #486).
    - Upsides: all the "downsides" listed above.
    - Downside: lookup leakage for slow .loki resolution (due to timeout).

Perhaps a sort-of-okay solution would be the second option but have lokinet DNS resolution return a not-found error after an internal timeout (chosen to be less than the usual system resolver timeout).

**Comment by jagerman** [comment]
Closely related: #573

**Comment by neuroscr** [comment]
our cname hack did work, I had a version on working with my implementation

**Comment by majestrate** [comment]
any updates on this?

**Comment by neuroscr** [comment]
Jason confirmed cname hack will close this issue

**Comment by jagerman** [comment]
For the record: the basic CNAME hack idea is:

1. on lookup of a new lokinet address (for example say `xyz.loki`) try to build a path
2. if we get to an internal timeout (e.g. 1 second) and haven't yet build the path, reply to the client that the address is a CNAME for `xyz-1.loki`, otherwise go to 5.
3. when lokinet gets a request for `xyz-{N}.loki` (for some numeric `{N}`) it strips the `-1` and tries (or continues to try) building a path to `xyz.loki`.
4. If we hit another 1s timeout, reply with a CNAME for `xyz-{N+1}.loki` (go back to step 3).
5. return the IP that maps to `xyz.loki`.

**Comment by majestrate** [comment]
On Wed, Sep 04, 2019 at 07:39:56PM -0700, Jason Rhinelander wrote:
> For the record: the basic CNAME hack idea is:
> 
> 1. on lookup of a new lokinet address (for example say `xyz.loki`) try to build a path
> 2. if we get to an internal timeout (e.g. 1 second) and haven't yet build the path, reply to the client that the address is a CNAME for `xyz-1.loki`, otherwise go to 5.
> 3. when lokinet gets a request for `xyz-{N}.loki` (for some numeric `{N}`) it strips the `-1` and tries (or continues to try) building a path to `xyz.loki`.
> 4. If we hit another 1s timeout, reply with a CNAME for `xyz-{N+1}.loki` (go back to step 3).
> 5. return the IP that maps to `xyz.loki`.

i was thinking of just appened it as a subdomain instead of at the end of the main name part becuase it would probably break less

**Comment by neuroscr** [comment]
being fast is good enough
but need to be able to say NOT FOUND explicitly tho
