### ISSUE TITLE
WIP RFC: config files to paths

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#585]
We have too many configureable filenames.
- I don't think we need flexibility (confusion) on the filenames themselve, just the directories
- it's very hard to make sure all files that we need to be persistence (in an environment like Docker where the home directory is not persistent)
- should individual enough to make debian package building happy (so debian place place everything in the proper directories)
... WIP, more coming

**Comment by majestrate** [comment]
On Fri, May 03, 2019 at 03:20:06PM -0700, Ryan Tharp wrote:
> We have too many configureable filenames.
> - I don't think we need flexibility (confusion) on the filenames themselve, just the directories
> - it's very hard to make sure all files that we need to be persistence (in an environment like Docker where the home directory is not persistent)
> - should individual enough to make debian package building happy (so debian place place everything in the proper directories)
> ... WIP, more coming
we have a generate config option for a reason

**Comment by neuroscr** [comment]
was a WIP haven't finish writing this.

**Comment by neuroscr** [comment]
just closing for now, I don't think we're changing config until next year
