### ISSUE TITLE
?? Crash

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#605]
**Describe the bug**
Client crashed, noticed when macos laptop woke from sleep

**To Reproduce**
??

**Screenshots Or Logs**
<img width="1297" alt="Screen Shot 2019-05-15 at 6 39 44 AM" src="https://user-images.githubusercontent.com/1224671/57781243-a257ef80-76de-11e9-9203-da12ff01a2fc.png">

**Device and Operating system (please complete the following information):**
 - OS: MacOS
-  Device: My macbook pro
 - Lokinet Version number or Git commit hash: 8bee0a3d

**Comment by majestrate** [comment]
updates?

**Comment by neuroscr** [comment]
I believe this was fixed in new york
