### ISSUE TITLE
Keyfile accepts directory

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-network#607]
**Describe the bug**
Giving Lokinet INI a directory instead of a filename for the keyfile does not cause an error message or shutdown

**To Reproduce**
Give the keyfile= a directory instead of filename

**Screenshots Or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Device and Operating system (please complete the following information):**
 - OS: Windows
-  Device: Windows
 - Lokinet Version number or Git commit hash: 0.4.1

**Comment by michael-loki** [comment]
ack, will look at this today.

**Comment by michael-loki** [comment]
Always help if you hit 'comment'....

It produces a warning message for me:

```
[WRN] (86) Fri May 17 13:41:07 2019 BST service/endpoint.cpp:502	Can't ensure keyfile [/Users/mthorpe/.lokinet/snapp/]
