### ISSUE TITLE
DHTutil: Please add callback/future to path builder

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#614]
I want to be able to set up a DHT query before the main loop and have the callback happen after the DHT is online and can be queried.

**Comment by michael-loki** [comment]
Do you want to be notified on *every* path build? Or just the one you set up?

**Comment by neuroscr** [comment]
just the one I set up

**Comment by michael-loki** [comment]
how are you setting up the DHT query right now?

**Comment by neuroscr** [comment]
This is how I was attempting it at the hackathon
https://github.com/loki-project/loki-network/pull/577/commits/352f5d32b58640037a21655a10bb6c3750c3f62d

**Comment by neuroscr** [comment]
closing, not enough buy-in
