### ISSUE TITLE
Include nickname in metric reports

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#624]
Because I have all the stdout dumping to the same place, I get stuff like this:
```
lokineterr: 2019-05-25T19:12:00.658633415-07:00
lokineterr:  1 Records
	Elapsed Time: 30.0019s
		utp.session.sendq.yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy.snode [ count = 6, total = 0, min = 0, max = 0 ]

lokineterr: 2019-05-25T19:12:00.687410852-07:00 1 Records

lokineterr: 	Elapsed Time: 30.0027s
		utp.session.sendq.ekbz6p14r1b3q8is16o1biyikt9enf8qgznqjxwzp4eqd4ar436o.snode [ count = 880, total = 0, min = 0, max = 0 ]
```
I can't tell if this is the seed/client or which router. I know this is a rare case, however it can't hurt to have it included, because you could forgot which one you're looking at when analyzing a bunch of data.

**Comment by neuroscr** [comment]
@michael-loki didn't you do this?

**Comment by michael-loki** [comment]
Not with nicknames, no
