### ISSUE TITLE
Can't build/mesh network over NAT

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#626]
**Describe the bug**
It doesn't works

**To Reproduce**
Run a bunch of routers behind NAT including the seed

**Screenshots Or Logs**
Just ask

**Device and Operating system (please complete the following information):**
 - OS: macos
-  Device: Mac Pro
 - Lokinet Version number or Git commit hash:
Most of the may commits of lokinet

**Comment by majestrate** [comment]
updates?

**Comment by neuroscr** [comment]
still broken
