### ISSUE TITLE
MacOS installer

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#63]
Install the lokinet command line tools and maybe the qt app when we have it

**Comment by liilac** [comment]
@majestrate @neuroscr should this issue be closed for now?  There's no graphical application to install, and command line tool installation is handled by the homebrew formula, which is separately tracked by #105, with PR #110 currently awaiting review.

**Comment by neuroscr** [comment]
No, homebrew doesn't address the requirement that this issue represents

**Comment by liilac** [comment]
If that's the case then I can prepare a standalone installer as discussed previously.

**Comment by neuroscr** [comment]
we have one now
