### ISSUE TITLE
Crashes on lokinet-0.4.3-755a2329

### ISSUE THREAD

**Issue by BeaudanBrown** [loki-project/loki-network#634]
Had several relays on the messenger net (all one box) last night
I sent the coredumps in lokinet-stability discord channel, (except for one that was 300MB?)
Here are the corresponding crash logs

lokinet9: `lokinet9: /home/beaudan/workspace/loki-network/libutp/utp_internal.cpp:1148: void UTPSocket::write_outgoing_packet(size_t, uint, utp_iovec*, size_t): Assertion `cur_window == 0' failed.`

lokinet3: No relevant log on crash, just silently crashed

lokinet8: `free(): corrupted unsorted chunks`

lokinet0 (300MB coredump): `malloc(): memory corruption`

**Comment by majestrate** [comment]
try https://github.com/loki-project/loki-network/commit/95b28a9fb57ab841b47abe684929e91ea0282696

**Comment by majestrate** [comment]
status?

**Comment by michael-loki** [comment]
this looks to be fixed
