### ISSUE TITLE
APT repo

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#64]
Would be cool to have an apt repo people could shove into their sources.list to get the latest releases

**Comment by neuroscr** [comment]
pointed out this is probably something that loki should host and control

**Comment by neuroscr** [comment]
Spin up a node on hetzner

**Comment by liilac** [comment]
Worth pointing out that GitLab's CI/CD is excellent at this sort of thing.

For now we can use GitLab.com runners and hosting for the packages, but it's of course something we can setup on Loki infrastructure.  However if it's just going to be hosted on hetzner or something, then I'd strongly suggest just using GitLab.com.

Relevant [article](https://about.gitlab.com/2016/10/12/automated-debian-package-build-with-gitlab-ci/) about automated Debian package builds.

I seem to be the one working on a lot of packaging stuff.  I can setup CI/CD for automated package builds for major platforms if that's desired?  Most platforms also have support for source packages; for example my current brew package exists solely as a formula (compiles from source).

**Comment by neuroscr** [comment]
I think we have a lokinet CI on gitlab.com already

**Comment by majestrate** [comment]
On Mon, Dec 10, 2018 at 11:14:51AM -0800, Ryan Tharp wrote:
> I think we have a lokinet CI on gitlab.com already
this is correct.

**Comment by neuroscr** [comment]
@majestrate do you have any details on that? a URL even?

**Comment by majestrate** [comment]
On Mon, Dec 10, 2018 at 11:18:46AM -0800, Ryan Tharp wrote:
> @majestrate do you have any details on that? a URL even?
it's here: https://gitlab.com/lokiproject/loki-network/

**Comment by despair86** [comment]
@jagerman set up apt repos not too long ago, link is in release page
