### ISSUE TITLE
Command line option to output logging as JSON

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#644]
date/time as a timestamp
nickname as a field
source code path as a field
etc

to make our log import/processing cleaner where we can

**Comment by majestrate** [comment]
to stdout or to file?

**Comment by neuroscr** [comment]
unspecified because either works, I'd prefer stdout atm

**Comment by majestrate** [comment]
merged via https://github.com/loki-project/loki-network/pull/645
