### ISSUE TITLE
Qubes OS 4.0 - Fedora 9 error : resolvconf and libuv1-dev

### ISSUE THREAD

**Issue by wJeZfAC** [loki-project/loki-network#656]
Followed your installation guide on
https://lokidocs.com/Lokinet/Guides/Install/

`sudo dnf install build-essential cmake libcap-dev wget git resolvconf curl libuv1-dev`
Last metadata expiration check: xx:xx:xx ago on Wed Jun 19 xx:xx:xx 2019.
No match for argument: build-essential
No match for argument: libcap-dev
Package wget-1.20.3-1.fc29.x86_64 is already installed.
Package git-2.20.1-1.fc29.x86_64 is already installed.
**No match for argument: resolvconf
No match for argument: libuv1-dev**
Error: Unable to find a match

checking wget
`rpm -qa wget`
wget-1.20.3-1.fc29.x86_64

checking curl
`curl -V`
curl 7.61.1 (x86_64-redhat-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.1b zlib/1.2.11 nghttp2/1.34.0
Release-Date: 2018-09-05

not sure if this is a Fedora, a Qubes or a user issue.

my setup:
A new Qubes VM; type: standalone qube based on a template
Template: default (fedora-29)

Any help or hint is welcome.

If I get this setup done I will send you a Qubes OS installation description.

**Comment by majestrate** [comment]
let's see if i can get the package names for those on fedora....

**Comment by majestrate** [comment]
looks like on federoa they just call it `libuv` since they don't package the older version.

as for resolvconf you'd probably have to bugger with `NetworkManager` settings and have it set dns resolvers with that, which is something we should support but I never allocated time for.

**Comment by neuroscr** [comment]
closing due to non-timely-response by opener
