### ISSUE TITLE
Update/Implement LTRP  

### ISSUE THREAD

**Issue by majestrate** [loki-project/loki-network#663]
last updated in october
https://github.com/loki-project/loki-network/blob/a582983a63b3b247169f710b928a720924aa25b5/docs/api_v0.txt

this is a protocol for spawning new hidden service endpoints and interacting with them. this is relevant to mobile apps, networking namespaces and anyone that needs to manage their own tun interface.

**Comment by majestrate** [comment]
this allows an application that has its own network interface to spin up its own isolated snapp endpoint that only it controls, this would essentially provide an easier way to do network sandboxing per application on mobile and desktop. this would help unify the codebase across mobile and non-mobile platforms as well as it would provide a simple "glue api" for speaking with the network. it also cuts out duplication of maintaince as you will just have the lokinet stuff in lokinet core and the ip tun stuff would be encapsulated for each platform and would use this protocol to speak with core. future efforts to port to other platforms would also be easier as you would implement this protocol instead of hacking on the core.

**Comment by majestrate** [comment]
in addition, this protocol needs to be updated and revised as it is currently last modified in October.

**Comment by neuroscr** [comment]
Niels says he's blocked waiting for Jeff to implement this. Jason says it's a priority for 0.6. @majestrate what is this blocked by?

**Comment by neuroscr** [comment]
need to have meeting with Niels

**Comment by neuroscr** [comment]
Android JNI bindings are done, lazy inject of tun interface
just need to pump the JNI binding into an android app

and then following the pattern for iOS

**Comment by majestrate** [comment]
no longer applicable
