### ISSUE TITLE
Windows implementation of SetThreadName

### ISSUE THREAD

**Issue by michael-loki** [loki-project/loki-network#689]
It’s done on other platforms, just not windows.

**Comment by despair86** [comment]
I have one already
I'll pull it back out, it's wrapped in `#if 0` block atm

**Comment by despair86** [comment]
and in fact, the only reason you'd need one is for MSVC builds as `pthread_setname_np(3)` is available under the MSYS2 build environment

**Comment by despair86** [comment]
fixed in my branch (see 19571cce1e29917d5a119f13ce263e3c55414376)
