### ISSUE TITLE
Non-overridable flags set

### ISSUE THREAD

**Issue by lesderid** [loki-project/loki-network#71]
Some non-overridable flags are set in [CMakeLists.txt](https://github.com/loki-project/loki-network/blob/3bf934782057ed2038b038d2fc114af2d88780b2/CMakeLists.txt):

https://github.com/loki-project/loki-network/blob/3bf934782057ed2038b038d2fc114af2d88780b2/CMakeLists.txt#L115-L127

Is this really necessary? I might want to build with `-march=native` on a system without AVX2. For example on my system there are quite a few differences: https://pst.moe/paste/njcmem

**Comment by majestrate** [comment]
yeah that's a bug.

**Comment by majestrate** [comment]
should be fixed as of now, let me know so i can close this issue.

**Comment by lesderid** [comment]
Looks fixed, thanks.
