### ISSUE TITLE
No bootstrapping possible

### ISSUE THREAD

**Issue by gh338** [loki-project/loki-network#718]
**Stuck at bootstrapping phase**
Bootstrapping is not working - no node connections possible

**Steps to reproduce**
Clean installation on Linux / Windows with release packages and git 

**Device and Operating system **
 - OS: [Ubuntu 18.04 + 18.10, Windows 10 64bit ]
-  Device: [ PC ]
 - Lokinet Version number or Git commit hash: 0.4.0 up to latest git commit

Issue #163 states to enable testnet segmenation but it's not evident to me on what exactly to do here.

**Comment by majestrate** [comment]
yeah looks like the bootstrap node only sees 2 other service nodes right now for some reason. let me recompile the binary for that and see if that helps it's probably really old.

**Comment by gh338** [comment]
> 
> 
> yeah looks like the bootstrap node only sees 2 other service nodes right now for some reason. let me recompile the binary for that and see if that helps it's probably really old.

It did help. Chat server name resolution is not working ( icxqqcpd3sfkjbqifn53h7rmusqa1fyxwqyfrrcgkd37xcikwa7y.loki
 ). Maybe it is related to this issue ?

**Comment by majestrate** [comment]
it shouldn't be related as that's just a random hidden service that is up not related to the bootstrap node.

**Comment by majestrate** [comment]
looks like the toy net fell apart from having too few nodes up, it should be back up now and we'll get more nodes with the next tagged release in a bit. @gh338
