### ISSUE TITLE
test core dumped

### ISSUE THREAD

**Issue by noalphakamp** [loki-project/loki-network#73]
ubuntu 18.04 gcc version 7.3.0 32core 96gb ram 
git commit 3bf934782057ed2038b038d2fc114af2d88780b2 

Makefile:149: recipe for target 'test' failed
make: *** [test] Illegal instruction (core dumped)

**Comment by noalphakamp** [comment]
git commit 1d0602100f2323d7d8136884886a00e16fbefe81
loki-network/test/test_llarp_queue_manager.cpp: In member function ‘virtual void TestQueueManager_SimpleUsage_Test::TestBody()’:
loki-network/test/test_llarp_queue_manager.cpp:98:15: error: ‘<anonymous>’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
       return {};
               ^
[ 99%] Built target rcutil
cc1plus: all warnings being treated as errors
CMakeFiles/testAll.dir/build.make:422: recipe for target 'CMakeFiles/testAll.dir/test/test_llarp_queue_manager.cpp.o' failed

make[2]: *** [CMakeFiles/testAll.dir/test/test_llarp_queue_manager.cpp.o] Error 1
CMakeFiles/Makefile2:300: recipe for target 'CMakeFiles/testAll.dir/all' failed
make[1]: *** [CMakeFiles/testAll.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lesderid** [comment]
Try building with `make AVX2=OFF`.

**Comment by majestrate** [comment]
i'll turn avx2 option off by default that will make it work

**Comment by majestrate** [comment]
updated in a8e3f7 let me know if that works.

**Comment by noalphakamp** [comment]
Works
