### ISSUE TITLE
icxqqcpd3sfkjbqifn53h7rmusqa1fyxwqyfrrcgkd37xcikwa7y.loki dns failure

### ISSUE THREAD

**Issue by gh338** [loki-project/loki-network#745]
**Describe the bug**
IRC dns resolution fails all the time

**To Reproduce**
run lokinet

**Screenshots Or Logs**
icxqqcpd3sfkjbqifn53h7rmusqa1fyxwqyfrrcgkd37xcikwa7y.loki

**Device and Operating system (please complete the following information):**
 - OS: [Ubuntu 18.04 LTS]
-  Device: [ PC ]
 - Lokinet Version number or Git commit hash: [ 0515ad6bf97ea56ba5885a09b98593fc568f2648 ]

Is there an alternative way to connect to that irc service other than lokinet ?
It work sporadically - but it's mainly broken.

**Comment by majestrate** [comment]
yes it should have a leaf at endchan.net and a few onions. icx got stuck when we flipped the net last night.

**Comment by gh338** [comment]
Okay so what do I do get into the chat again ?

**Comment by majestrate** [comment]
icx seems unstuck so restart lokinet and try again.

**Comment by gh338** [comment]
Working again - thank you.
