### ISSUE TITLE
Clang build fails because of `CMAKE_CXX_STANDARD 11`

### ISSUE THREAD

**Issue by lesderid** [loki-project/loki-network#77]
From PR https://github.com/loki-project/loki-network/pull/70:
> Building fails with clang with `CMAKE_CXX_STANDARD 11`: `lokinet/test/test_llarp_queue_manager.cpp:142:56: error: static_assert with no message is a C++17 extension [-Werror,-Wc++17-extensions]`

**Comment by michael-loki** [comment]
fixed by #76
