### ISSUE TITLE
Need minimal TLS library for https server and client

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#80]
libabyss can use the server portions
and secure DNSc can use the client portion (and is blocking)

Maybe obsoleted if we include a stripped libmbed

**Comment by liilac** [comment]
What is this being used for?

**Comment by majestrate** [comment]
On Sun, Dec 09, 2018 at 10:22:15AM -0800, Rick V wrote:
> hmm
> you have anything against the ApacheII licence? @majestrate 
i am unfamiliar with the clauses of it but not against it.

**Comment by neuroscr** [comment]
@liilac for an admin API that other loki services will use and I was going to use such a library for DNS requests over HTTPS to increase security but not sure what's going on with the DNS project now

**Comment by neuroscr** [comment]
Why can't we make the micronetrunner more cross platform and just use that?

**Comment by despair86** [comment]
because everyone else has cURL or wget and a Bourne shell

on the other hand, there's only a few hardcoded strings that assume NT, so....

*shrugs* (why not?)

**Comment by neuroscr** [comment]
@majestrate says we're fine to go forward with mbed for now
