### ISSUE TITLE
Lokid <=> lokinet zmq refresh

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#808]
- make sure existing whitelist update is working (did any changes since may break this)
- The following:
  - add a "storage server like" endpoint in lokid
  - lokinet will periodically hit this endpoint to show that it's alive for the uptime proof

**Comment by majestrate** [comment]
for uptime proof we could have lokinet sign a part of the proof

**Comment by neuroscr** [comment]
use new ed25519 keypair

**Comment by neuroscr** [comment]
Jason wants to re-engineer this

**Comment by neuroscr** [comment]
Stephen removed libabyss so we can't integrate dev branch with lokid..
we'll replace with libcurl or zmq
