### ISSUE TITLE
Network connection fails after period of inactivity 

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-network#813]
**Describe the bug**
when i come back into work after not connecting to Lokinet over the weekend it will not make a connection to the network, the client spams these errors over and over again. 

```
[NFO] [lokinet](656) 09/09/19 01:38:35 UTC [+222446 ms] router/router.cpp:703    connecting to 4 random routers to keep alive
[WRN] [lokinet](656) 09/09/19 01:38:35 UTC [+222446 ms] path/pathbuilder.cpp:401    default:g1xzrgfijz1dkr7y79kuwmo6e7wosbc3k1pgqga38cdsnquwdt9y.loki failed to select hop 0
[NFO] [lokinet](656) 09/09/19 01:38:36 UTC [+223505 ms] router/router.cpp:703    connecting to 4 random routers to keep alive
[WRN] [lokinet](656) 09/09/19 01:38:36 UTC [+223505 ms] path/pathbuilder.cpp:401    default:g1xzrgfijz1dkr7y79kuwmo6e7wosbc3k1pgqga38cdsnquwdt9y.loki failed to select hop 0
```

I can fix the client by downloading the bootstrap from https://seed.lokinet.org/bootstrap.signed
so it seems like something wacky is going on here 

**To Reproduce**
Don't connect a Lokinet client to the network for a few days and then try and connect to the network again 

**Screenshots Or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Device and Operating system (please complete the following information):**
 - OS: Only tested on Windows so far, but same bug was experienced on two separate machines  
-  Device: PC
 - Lokinet Version number or Git commit hash: 5.0.0 from Releases

**Comment by jagerman** [comment]
I didn't see this on my linux laptop (which has been offline for a few days).  It was still on the internal "bugs" net, and from a build of master from about a week ago, but upon starting lokinet I didn't get the same errors and could ping bugs-net snodes.  So *possibly* Windows-specific?

**Comment by KeeJef** [comment]
looks like this was fixed here https://github.com/loki-project/loki-network/pull/814
