### ISSUE TITLE
remove all exe files from source tracking and build them from source.

### ISSUE THREAD

**Issue by majestrate** [loki-project/loki-network#816]
cc @despair86

**Comment by despair86** [comment]
mostly done
windows drivers, 7-zip, bootstrap all moved to off-site location and downloaded at runtime, bootstrap is downloaded at build time (see `win32-setup/Makefile`)
registry helper lib built on-demand

**Comment by despair86** [comment]
move to #825

**Comment by despair86** [comment]
closed in #825
