### ISSUE TITLE
add windows installer target as makefile target

### ISSUE THREAD

**Issue by majestrate** [loki-project/loki-network#817]
i want to be able to build the windows install via make

**Comment by despair86** [comment]
installer also packages the UI, requires mono or coreclr to build if you want to use wine

**Comment by majestrate** [comment]
that's fine

**Comment by despair86** [comment]
90% of it done in #825, still seeking info on how to trigger travis ci to do so, `dotnet35` choco pkg is broken ;-;

**Comment by despair86** [comment]
ok so i'm pushing this back until qt5 ui lands (by which time the winforms UI will be a fully optional component)

**Comment by despair86** [comment]
ok 95% complete see above (most merged in #864)

**Comment by majestrate** [comment]
this has been accomplished as of `0.8.1`
