### ISSUE TITLE
macOS 10.14 error

### ISSUE THREAD

**Issue by DiCE1904** [loki-project/loki-network#821]
Trying to get Lokinet working on my mac following the guide. 
After installing the lastest version 0.5.1 , going into `cd /usr/local/bin`
```
./lokinet -g
dyld: Library not loaded: @rpath/libuv.dylib
  Referenced from: /usr/local/bin/./lokinet
  Reason: image not found
Abort trap: 6
```

**Comment by neuroscr** [comment]
Just posted an updated 0.5.1 installer to the releases, please now try with that. That should have the libuv shared library bundled correctly.

**Comment by DiCE1904** [comment]
The new one did the trick, working now. Thanks!
