### ISSUE TITLE
Path Handover timeouts 

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-network#826]
**Describe the bug**
When path handover occurs clients experience a brief period of timeouts with connections to hidden services of about 1-5 seconds  

**To Reproduce**

Run a Lokinet client and continually ping a hidden service, you should see regular peroids where timeouts occur which coincide with  a path handover.

**Screenshots Or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Device and Operating system (please complete the following information):**
 - OS: [e.g. iOS, Windows, Android] Confirmed on Windows and Linux
-  Device: [ e.g. Mac, PC, IPhone] PC
 - Lokinet Version number or Git commit hash: 0.5.1

**Comment by majestrate** [comment]
fixed by #834
