### ISSUE TITLE
MacOS Crash on start

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#835]
Posted 1.4 gb core in private discord and Michael said to make an issue

**Comment by majestrate** [comment]
On Thu, Sep 19, 2019 at 11:45:34PM -0700, Ryan Tharp wrote:
> Posted 1.4 gb core in private discord and Michael said to make an issue
the crash is in the metrics code, i think. we should disable metrics.

**Comment by michael-loki** [comment]
I spent some of friday, and much of today, digging into this. I actually managed to temporarily reproduce it after rebasing on top of `master` earlier today, but then a clean build fixed the issue for me.

**Comment by michael-loki** [comment]
Just seen this trace on my mac again (or something similar)

**Comment by michael-loki** [comment]
Okay, what I think has happened.

Something about the migration to use `-DSTATIC_LINK=ON` (and LTO) for release builds broke some object in abseil (but also possibly in llarp), which was exacerbated by hitting an atomic int. 

Cleaning the build completely *and* cleaning anything left around by ccache (via `ccache -c`) should be sufficient to resolve this issue permanently.
