### ISSUE TITLE
Make lokinet startup do nothing until it receives an enable/disable

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#853]

**Comment by despair86** [comment]
add a `--daemon` flag to run in the old way

**Comment by neuroscr** [comment]
How about —start instead?

**Comment by majestrate** [comment]
so `--start` would tell lokinet to NOT start anything until they get a command to do so?

**Comment by michael-loki** [comment]
I’m making this “keep current behaviour”, and adding a `—background` flag which starts in the background, but doesn’t start DNS etc, just has the jsonrpc stuff running.

**Comment by neuroscr** [comment]
@majestrate I meant `--start` to run the old way (auto-enabled) but I think @michael-loki's suggestion makes more sense. All of us Devs and CLI people are going to expect it to auto-start for the most part, only the GUI starters need it delayed.

**Comment by michael-loki** [comment]
this is done.
