### ISSUE TITLE
TunTap Hook for iOS

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#854]
Jeff to produce mobile API 10/2/19
"custom tun injection shit from c api"

**Comment by neuroscr** [comment]
merged into #663

**Comment by neuroscr** [comment]
Re-opening, since Jeff considered #663 no longer relevant. Copying over this last comment:

Android JNI bindings are done, lazy inject of tun interface (not merged, hopefully merged by end of the week)
just need to pump the JNI binding into an android app

and then following the pattern for iOS

**Comment by majestrate** [comment]
#529 is a more concrete variant of this bug.
