### ISSUE TITLE
Routers become invalid over time

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#867]
**Describe the bug**
Eventually all your nodedb are invalid and you may need to re-bootstrap or delete everything in the nodedb

You can't build paths. Sometimes a restart fixes this, other times re-bootstrap is also required. Kee says he's been deleting his nodedb to fix it

**To Reproduce**
Leave lokinet running for more than 24 hours

**Screenshots Or Logs**
See internal discord

**Device and Operating system (please complete the following information):**
 - OS: all
-  Device: all
 - Lokinet Version number or Git commit hash: 0.5.2

**Comment by majestrate** [comment]
this happens because we for some reason do not connect out to nodes in some unknown case which makes it so we cannot update RCs from the network which cause them to be expunged after a little bit of time.

**Comment by majestrate** [comment]
the real problem isn't related to RC expiration it's related to link sessions not being made

**Comment by neuroscr** [comment]
What's the expunge period? and why isn't that off at this stage?

**Comment by majestrate** [comment]
lokinet still needs to expunge dead routers but does so if it cannot look them up from the dht enough times. if dht lookups fail for every router then you run out of RCs
