### ISSUE TITLE
Exit ignored

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-network#88]
Seems like the `Exit` command is being ignored in the lokinet console

This was on Ubuntu 18.04 latest head 387d05282b5df99592df47e82921015d787708d7

**Comment by majestrate** [comment]
are you sending `SIGTERM` or `SIGINT`?

**Comment by majestrate** [comment]
looks like only `SIGINT` is handled and not `SIGTERM` will fix shortly

**Comment by majestrate** [comment]
try https://github.com/loki-project/loki-network/commit/a811d1138ddd4a93650e620698584d30ab14031a

**Comment by majestrate** [comment]
is this fixed on your end? may i close it?

**Comment by KeeJef** [comment]
Updated to head on master and this still fails 

> [NFO] unnamed (608) Tue Dec  4 13:07:39 2018 AEDT llarp/router.cpp:56	established session with f08b5e947e49f4a7831e2789b6f3c948ec9320c7d3fac7d88a5e9dd08515d4df
[NFO] unnamed (608) Tue Dec  4 13:07:40 2018 AEDT llarp/path.cpp:412	path TX=220e8b414495f665aa64a9d872be9d2c RX=42aa1bc01ae991dcee6a2ecaff8f1737 is building
exit
[NFO] unnamed (608) Tue Dec  4 13:07:48 2018 AEDT llarp/handlers/tun.cpp:583	Failed to parse ipv4 packet
buffer of size 48
`.....:............Y*..y........................
[NFO] unnamed (608) Tue Dec  4 13:07:51 2018 AEDT llarp/path.cpp:412	path TX=fcd8c634af194812fdc3ddcdf677a6b7 RX=a3286e624d91dacfc647d916df19a411 is building
[NFO] unnamed (608) Tue Dec  4 13:07:51 2018 AEDT llarp/pathset.cpp:281	path TX=dcce43e30572a42cb46ef6d658c22f22 RX=dc96f996927495a29fec0cd0e1b313fc has timed out
^C[ERR] unnamed (608) Tue Dec  4 13:07:51 2018 AEDT llarp/link/utp.cpp:406	sendto failed: Bad file descriptor
[ERR] unnamed (608) Tue Dec  4 13:07:51 2018 AEDT llarp/link/utp.cpp:406	sendto failed: Bad file descriptor
[ERR] unnamed (608) Tue Dec  4 13:07:51 2018 AEDT llarp/link/utp.cpp:406	sendto failed: Bad file descriptor
[ERR] unnamed (608) Tue Dec  4 13:07:51 2018 AEDT llarp/link/utp.cpp:406	sendto failed: Bad file descriptor
[ERR] unnamed (608) Tue Dec  4 13:07:51 2018 AEDT llarp/link/utp.cpp:406	sendto failed: Bad file descriptor

**Comment by neuroscr** [comment]
There is no lokinet console, nor do I think there should be one. (Popular daemons like Apache/Nginx, MySQL and tor do not have one) We have the RPC server and the signal handlers.

**Comment by majestrate** [comment]
typing exit shouldn't have any effect as lokinet doesn't read `stdin` for commands like lokid does.
`SIGINT` or `SIGTERM` should suffice as with every other daemon out there.
