### ISSUE TITLE
DNS crashes on MacOS

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#894]
**Describe the bug**
DNS crashes lokinet on MacOS

**To Reproduce**
`ping random.snode`

**Screenshots Or Logs**
```
[NFO] [macpro-master](201) Thu Oct 31 14:56:47 2019 PDT [+1896 ms] router/outbound_session_maker.cpp:41	session with router [1f8984y3g9xos3i7yggdzi8zmexwmsowen9e4jmrydaktxz14ewy.snode] established
NullMutex 0x7fac4ff02048 was locked by 0x70000104b000 and was previously locked by 0x7000010ce000
Abort trap: 6
```

**Device and Operating system (please complete the following information):**
 - OS: MacOS 10.14
-  Device: MacPro
 - Lokinet Version number or Git commit hash: 233684fc

**Comment by majestrate** [comment]
fixed by https://github.com/loki-project/loki-network/commit/30fa45fa055d892b662b8ab6431d5e4a2f8fc58f (probably)
