### ISSUE TITLE
Unable to Resolve .loki address with running lokinet service in Ubuntu 18.04

### ISSUE THREAD

**Issue by ChanoSan** [loki-project/loki-network#908]
**Describe the bug**
On Ubuntu 18.04, with latest version of lokinet installed via the deb.imaginary.stream repo, Regular internet access works, but I am unable to reach any .loki addresses, and all traffic appears to be unobfuscated. I have confirmed that the service is _active (running)_ via both _sudo systemctl status lokinet_ and _sudo service lokinet status_ .

Following instructions in docs.loki.network, I have tested bootstrapping, which results in _lokinet successfully bootstrapped_ . Even after restarting the lokinet service, the problem persists.

I have also attempted both resolvconf methods listed in the Troubleshooting section of the Linux Guide, but it has no effect. I have tried different browsers, have stopped and restarted the service, have rebooted the system, and have even attempted uninstalling and reinstalling the lokinet package, but the problem persists regardless.

I have successfully used lokinet installed from the same source, on the same PC with no issue one month ago (early October). I returned after about a month, updated all packages this week (early November) when problems began.

I attempted an _nslookup_ of a lokinet address, which resulted in an NXDOMAIN error (log included below).

Although I doubt this is necessary for the functioning of lokinet, I attempted to run the command _lokinet_ at the CLI just to see if anything would happen, and it returned an error (log included below).

Is there anything more I can do to attempt to fix this?

**Screenshots Or Logs**
NSLOOKUP
$ nslookup zqkddypocxnu3r53ddy6hkogcdi1xz6kcitjjsh483jom336wo5y.loki
Server:     127.0.0.53
Address:   127.0.0.53#53

** server can't find zqkddypocxnu3r53ddy6hkogcdi1xz6kcitjjsh483jom336wo5y.loki: NXDOMAIN

USE OF _LOKINET_ COMMAND
[ERR] [lokinet](366) Sun Nov 10 00:45:08 2019 JST [+0 ms] config/config.cpp:493generic:2

**Device and Operating system (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
-  Device: PC
 - Lokinet Version number or Git commit hash: Version 0.5.2-4~ubuntu1804

**Comment by majestrate** [comment]
On Sat, Nov 09, 2019 at 07:48:28AM -0800, Andrew Onishi wrote:
> **Describe the bug**
> On Ubuntu 18.04, with latest version of lokinet installed via the deb.imaginary.stream repo, Regular internet access works, but I am unable to reach any .loki addresses, and all traffic appears to be unobfuscated. I have confirmed that the service is _active (running)_ via both _sudo systemctl status lokinet_ and _sudo service lokinet status_ .
> 
> Following instructions in docs.loki.network, I have tested bootstrapping, which results in _lokinet successfully bootstrapped_ . Even after restarting the lokinet service, the problem persists.
> 
> I have also attempted both resolvconf methods listed in the Troubleshooting section of the Linux Guide, but it has no effect. I have tried different browsers, have stopped and restarted the service, have rebooted the system, and have even attempted uninstalling and reinstalling the lokinet package, but the problem persists regardless.
> 
> I have successfully used lokinet installed from the same source, on the same PC with no issue one month ago (early October). I returned after about a month, updated all packages this week (early November) when problems began.
> 
> I attempted an _nslookup_ of a lokinet address, which resulted in an NXDOMAIN error (log included below).
> 
> Although I doubt this is necessary for the functioning of lokinet, I attempted to run the command _lokinet_ at the CLI just to see if anything would happen, and it returned an error (log included below).
> 
> Is there anything more I can do to attempt to fix this?
> 
> **Screenshots Or Logs**
> NSLOOKUP
> _$ nslookup zqkddypocxnu3r53ddy6hkogcdi1xz6kcitjjsh483jom336wo5y.loki
> Server:     127.0.0.53
> Address:   127.0.0.53#53
> 
> USE OF _LOKINET_ COMMAND
> [ERR] [lokinet](366) Sun Nov 10 00:45:08 2019 JST [+0 ms] config/config.cpp:493generic:2
> 
> ** server can't find zqkddypocxnu3r53ddy6hkogcdi1xz6kcitjjsh483jom336wo5y.loki: NXDOMAIN_
> 
> **Device and Operating system (please complete the following information):**
>  - OS: Ubuntu 18.04.3 LTS
> -  Device: PC
>  - Lokinet Version number or Git commit hash: Version 0.5.2-4~ubuntu1804
> 

lokinet provides dns on 127.3.2.1 so it looks like your system resolver settings have not been hooked correctly by the systemd unit.

**Comment by ChanoSan** [comment]
> 
> On Sat, Nov 09, 2019 at 07:48:28AM -0800, Andrew Onishi wrote: **Describe the bug** On Ubuntu 18.04, with latest version of lokinet installed via the deb.imaginary.stream repo, Regular internet access works, but I am unable to reach any .loki addresses, and all traffic appears to be unobfuscated. I have confirmed that the service is _active (running)_ via both _sudo systemctl status lokinet_ and _sudo service lokinet status_ . Following instructions in docs.loki.network, I have tested bootstrapping, which results in _lokinet successfully bootstrapped_ . Even after restarting the lokinet service, the problem persists. I have also attempted both resolvconf methods listed in the Troubleshooting section of the Linux Guide, but it has no effect. I have tried different browsers, have stopped and restarted the service, have rebooted the system, and have even attempted uninstalling and reinstalling the lokinet package, but the problem persists regardless. I have successfully used lokinet installed from the same source, on the same PC with no issue one month ago (early October). I returned after about a month, updated all packages this week (early November) when problems began. I attempted an _nslookup_ of a lokinet address, which resulted in an NXDOMAIN error (log included below). Although I doubt this is necessary for the functioning of lokinet, I attempted to run the command _lokinet_ at the CLI just to see if anything would happen, and it returned an error (log included below). Is there anything more I can do to attempt to fix this? **Screenshots Or Logs** NSLOOKUP _$ nslookup zqkddypocxnu3r53ddy6hkogcdi1xz6kcitjjsh483jom336wo5y.loki Server: 127.0.0.53 Address: 127.0.0.53#53 USE OF _LOKINET_ COMMAND [ERR] [lokinet](366) Sun Nov 10 00:45:08 2019 JST [+0 ms] config/config.cpp:493generic:2 ** server can't find zqkddypocxnu3r53ddy6hkogcdi1xz6kcitjjsh483jom336wo5y.loki: NXDOMAIN_ **Device and Operating system (please complete the following information):** - OS: Ubuntu 18.04.3 LTS - Device: PC - Lokinet Version number or Git commit hash: Version 0.5.2-4~ubuntu1804
> lokinet provides dns on 127.3.2.1 so it looks like your system resolver settings have not been hooked correctly by the systemd unit.
> […](#)
> -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #908

Would that be governed by _systemd-resolved_ ? Does lokinet require it to function, or would I be able to stop/disable it to see if that fixes matters?

**Comment by ChanoSan** [comment]
Addendum: attempting nslookup with an obviously false URL, or putting anything before (_http://, https://_) or after (_/wiki_) results in:

_Server: 127.3.2.1
Address: 127.3.2.1#53_

with the same NXDOMAIN error.

Further, looking up a valid domain also calls 127.3.2.1

Only loking up a _longassstringoflettersandnumbers.loki_ format with nslookup results in it calling 127.0.0.53

**Comment by ChanoSan** [comment]
Pursuant to #911, I attempted to delete nodedb so resolve the issue, but was unable to figure out how.
I fell back to uninstalling the lokinet package and cloning/building from source instead.
.loki addresses are now reachable. While I technically only circumvented rather than solved the issue, I'll opt to close this regardless.
