### ISSUE TITLE
bootstrap.signed is empty

### ISSUE THREAD

**Issue by ebrand0007** [loki-project/loki-network#910]
the signed key on https://seed.lokinet.org/bootstrap.signed is zero length

**Comment by majestrate** [comment]
that's   ...... not good. cc @jagerman

**Comment by majestrate** [comment]
okay fixed, the disk got full and the file didn't get updated correctly

**Comment by ebrand0007** [comment]
Thank you...up and running now

**Comment by majestrate** [comment]
yw
