### ISSUE TITLE
0 hop bug

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#911]
we all know about it at this point... just creating a stub for tracking purposes

(I had meant for #867 to be this but turned out to be a bigger issue)

**Comment by ChanoSan** [comment]
In reference to Issue #908 , I noticed that _sudo systemctl status lokinet_ returns messages like:

**_default:[lokiaddresshere].loki failed to select hop 0_**

Is this the same issue as the 0 Hop Bug? And would deleting nodedb help resolve the issue?

**Comment by majestrate** [comment]
On Sat, Nov 16, 2019 at 07:01:06AM -0800, Andrew Onishi wrote:
> In reference to Issue #908 , I noticed that _sudo systemctl status lokinet_ returns messages like:
> 
> **_default:[lokiaddresshere].loki failed to select hop 0_**
> 
> Is this the same issue as the 0 Hop Bug? And would deleting nodedb help resolve the issue?

yes and yes.
