### ISSUE TITLE
Version & backup private key files

### ISSUE THREAD

**Issue by jagerman** [loki-project/loki-network#918]
0.6 will change key formats, which means existing installation's *.private files are going to become invalid.

We need a couple things to handle this migration (and future ones):
- adding a version tag to the file (currently they have a protocol version, but we want an independent versioning on it).
- when loading a private file, if the version is old then move aside the file to a backup filename (or subdir?) and generate a new one.  For 0.6 we just have a whole new one, but for version private file versions we probably will want to preserve things like the key pair.

**Comment by neuroscr** [comment]
merged

**Comment by jagerman** [comment]
Fixed by #921
