### ISSUE TITLE
Builds fail on AMD without flags

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-network#93]
Builds still failing with fastadd errors if make is not passed 

`CFLAGS='-march=haswell -mfma' CXXFLAGS='-march=haswell -mfma'`

We should include some kind of fix for this since AMD architecture is very common and we don't want people to have to go searching for the flags just to build Lokinet

`In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include/immintrin.h:85:0,
                 from /home/dev/loki-network/crypto/libntrup/src/avx/mult.c:3:
/home/dev/loki-network/crypto/libntrup/src/avx/mult.c: In function ‘fastadd’:
/usr/lib/gcc/x86_64-linux-gnu/7/include/fmaintrin.h:63:1: error: inlining failed in call to always_inline ‘_mm256_fmadd_ps’: target specific option mismatch
 _mm256_fmadd_ps (__m256 __A, __m256 __B, __m256 __C)
 ^~~~~~~~~~~~~~~
/home/dev/loki-network/crypto/libntrup/src/avx/mult.c:128:10: note: called from here
   return _mm256_fmadd_ps(y, v1_float, x);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include/immintrin.h:85:0,
                 from /home/dev/loki-network/crypto/libntrup/src/avx/mult.c:3:
/usr/lib/gcc/x86_64-linux-gnu/7/include/fmaintrin.h:63:1: error: inlining failed in call to always_inline ‘_mm256_fmadd_ps’: target specific option mismatch
 _mm256_fmadd_ps (__m256 __A, __m256 __B, __m256 __C)
 ^~~~~~~~~~~~~~~
/home/dev/loki-network/crypto/libntrup/src/avx/mult.c:128:10: note: called from here
   return _mm256_fmadd_ps(y, v1_float, x);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

This issue is a replication of #92

**Comment by despair86** [comment]
```
Zen: WikiChip's testing shows FMA4 still appears to work (under the conditions of the tests) despite not being officially supported and not even reported by CPUID. This has also been confirmed by Agner.[5] But other tests gave wrong results.[6] AMD Official Web Site FMA4 Support Note ZEN CPUs = AMD ThreadRipper 1900x, R7 Pro 1800, 1700, R5 Pro 1600, 1500, R3 Pro 1300, 1200, R3 2200G, R5 2400G.[7][8][9]
```

**Comment by KeeJef** [comment]
We should work out how to do CPU detection to rectify this bug its really annoying :(

**Comment by KeeJef** [comment]
confirming that https://github.com/loki-project/loki-network/pull/138 fixes this for me

**Comment by neuroscr** [comment]
@KeeJef you mean AMD_RYZEN_HACK makes it compile for you?

I'd like to keep the issue open until we can actually get a build-time test, if that's possible.

**Comment by KeeJef** [comment]
Yes AMD_RYZEN_HACK makes it compile without needing the above flags

**Comment by despair86** [comment]
ye

that's because it fills in those flags for you `-march=native -mavx -mavx2 -mfma -mfpmath=sse` (yes that last one is there because multilib)
