### ISSUE TITLE
lokinet is hammering lokid

### ISSUE THREAD

**Issue by notlesh** [loki-project/loki-network#946]
Per Jason:

Lokinet is hitting lokid's HTTP API once per second, which can be a performance issue when a large amount of data is returned.

API endpoint: `get_end_service_nodes`

Pass along `poll_block_hash` parameter, which will cause the API to return the current block's hash along with the normal dataset. This can then be passed to the API on subsequent calls, which will cause it to omit a full dataset if there is no new block.

Also, change the interval of the ping API call to 5 minutes.

Jeff: can use `tcpdump` to view user agent, which should include the string "YOLO" if it really is lokinet's HTTP client.

**Comment by jagerman** [comment]
Another place it's hammering it: on startup if it fails to fetch a key it looks like it tries again immediately to retrieve it.  It'd be nice to pause at least for a few seconds between failed retrieval attempts.  (Say 5s?)

**Comment by jagerman** [comment]
It also won't die when it's in a loop trying to retrieve keys.

**Comment by neuroscr** [comment]
was storage server

work might be done (according to Jeff)

**Comment by neuroscr** [comment]
#808 should also help
