### ISSUE TITLE
-h should be more descriptive

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#99]
Kee says should be something like

```
Usage: ./lokid [options|settings] [daemon_command...]

Options:
  --help                                Produce help message
  --version                             Output version information
  --os-version                          OS for which this executable was 
                                        compiled
```

**Comment by liilac** [comment]
I guess, though it increases the maintenance burden and makes it easier to miss things like this.  I'm sure lightweight libraries exist for this.

**Comment by majestrate** [comment]
On Sun, Dec 09, 2018 at 05:31:07AM -0800, Lilac wrote:
> I guess, though it increases the maintenance burden and makes it easier to miss things like this.  I'm sure lightweight libraries exist for this.
> 
man 3 getopt

**Comment by KeeJef** [comment]
Just going to ping this issue since we had a user mention in telegram today that this would be helpful

**Comment by liilac** [comment]
I'd be interested in implementing this if there's still interest, @KeeJef.

Is there still a firm position against using a lightweight (abstracting) library for this?  Got a firm no from @majestrate last time.

**Comment by michael-loki** [comment]
In #518, we’re adding a vendored dep on cxxopts, could be extended to do more easily.

**Comment by majestrate** [comment]
On Tue, Apr 16, 2019 at 12:47:28AM -0700, Lilac wrote:
> I'd be interested in implementing this if there's still interest, @KeeJef.
> 
> Is there still a firm position against using a lightweight (abstracting) library for this?  Got a firm no from @majestrate last time.

micheal has a patch for this rn. i think.

**Comment by neuroscr** [comment]
new help is in place
```
LokiNET is a free, open source, private, decentralized, "market based sybil resistant" and IP based onion routing network
Usage:
  lokinet [OPTION...] positional parameters

  -v, --verbose     Verbose
  -h, --help        help
  -g, --generate    generate client config
  -r, --router      generate router config
  -f, --force       overwrite
      --config arg  path to configuration file

```

if that looks good @KeeJef pls close
