### ISSUE TITLE
Static builds are not entirely static

### ISSUE THREAD

**Issue by jagerman** [loki-project/loki-network#995]
Currently static builds appear to still be dynamically linking to libcurl and libuv (and possibly libsodium, when not downloading?  Unconfirmed).  We need some cmake fiddling to link them statically when doing a static build.

**Comment by majestrate** [comment]
linking to libuv statically can be done using `-DLIBUV_ROOT=/path/to/libuv/source/code`

**Comment by neuroscr** [comment]
#1002 adds a `-DCURL_ROOT=/path/to/libcurl/source/code` and should wrap up the rest of this ticket

**Comment by majestrate** [comment]
fixed in https://github.com/loki-project/loki-network/pull/1005
